### ISSUE TITLE
3.8.1 endgame

### ISSUE THREAD

**Issue by CsCherrYY** [microsoft/vscode-gradle#1048]
cc: @testforstephen 

To verify:
- [x] https://github.com/microsoft/vscode-gradle/issues/1022

1. Open a new Gradle project. e.g. https://github.com/microsoft/vscode-gradle
2. Waiting for configuring projects process finished
3. Try to input `ja` in the root `build.gradle` file
    - There should be a `java(Closure c)` auto completion candidate 

4. Choose the one in step 3, in the java closure, try to input `so`
    - There should be a `sourceCompatibility` property candidate

- [x] https://github.com/microsoft/vscode-gradle/issues/1026

1. git clone https://gitee.com/mozhuanzuojing/java-bug01.git
2. git checkout `272b2842`
3. Open this project, after `get projects` process finished, check if there is any error report
    - Shouldn't report any error

4. In line 74, try to change `AttributeCompatibilityRule` to `AttributeCompatibilityRule1`, to see if there is any error report
    - Should report one error

- [x] https://github.com/microsoft/vscode-gradle/pull/1036

1. git clone https://github.com/microsoft/vscode-gradle
2. Delete `./gradlew`, `./gradlew.bat`, `./gradle/` from the root folder.
3. Open the folder in VSCode
    - vscode-gradle extension should activate normally

4. Change setting: `java.import.gradle.wrapper.enabled` to `false`, `java.import.gradle.version` to `6.8.1`
5. Check the output of `Gradle for Java`
    - The project should be configured successfully, using gradle version 6.8.1

- [x] https://github.com/microsoft/vscode-gradle/issues/1001

1. git clone https://gitee.com/mozhuanzuojing/java-bug01.git
2. git checkout `272b2842`
3. Open this project, open `Gradle` in the activity bar, check the configure results in `Gradle for Java` output
    - The Chinese results are shown correctly

- [x] https://github.com/microsoft/vscode-gradle/issues/1021
1. To verify: The extension is `Gradle for Java`
2. The home page of the extension: the document content should be properly

**Comment by testforstephen** [comment]
Endgame issues:
- https://github.com/microsoft/vscode-gradle/issues/1050
- https://github.com/microsoft/vscode-gradle/issues/1051
- https://github.com/microsoft/vscode-gradle/issues/1052

And try https://gitee.com/mozhuanzuojing/java-bug01.git, it seems most completion doesn't work in this sample project.
