### ISSUE TITLE
Throw errors when opening a non wrapper gradle project

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-gradle#1050]
The Gradle Projects view works well, but find some errors reported by output channel.

[error] [gradle-server] Error running gradle wrapper: Cannot run program "/Users/<myName>/Work/samples/TestGradle/gradlew" (in directory "/Users/<myName>/Work/samples/TestGradle"): error=2, No such file or directory
[error] Unable to get daemon status: Error running gradle wrapper: Cannot run program "/Users/<myName>/Work/samples/TestGradle/gradlew" (in directory "/Users/<myName>/Work/samples/TestGradle"): error=2, No such file or directory

**Comment by CsCherrYY** [comment]
here includes two issues:
- [ ] Should check `./gradle/gradle-wrapper.properties` file, rather than `./gradlew` file
- [ ] Should check wrapper in get daemon handler as well.
