### ISSUE TITLE
No completion suggestions for some cases such as "plugins", "mainClass" 

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-gradle#1052]
![image](https://user-images.githubusercontent.com/14052197/138815770-a1dbe8b0-93ec-4009-80c9-da4f202d83d5.png)
No completion for "plugins" closure.

![image](https://user-images.githubusercontent.com/14052197/138815844-75bc0a18-3fa7-42e6-8229-731e924e4a22.png)
No completion for "mainClass" property. Meanwhile "mainClassName" property is deprecated, should show a deprecated tag for it.

**Comment by CsCherrYY** [comment]
#1053 solves managed properties, deprecated tag will be solved in another PR.
