### ISSUE TITLE
No connection to the gradle server. Try restarting the server.

### ISSUE THREAD

**Issue by jdavies** [microsoft/vscode-gradle#137]
**Describe the bug**
I just started seeing this error reported in VSCode yesterday. If I disable the extension obviously the errors stop appearing. Directly beneath that error dialog in VSCode is a second one that says: "The terminal process terminated with exit code: 127"

I haven't added any new extensions to my development environment in the last week or so. According the the VSCode extension, it is running v2.4.2. Any idea what may be going on? I'm happy to provide additional detail as needed.

**To Reproduce**
Start VS Code, allow for all analysis and extensions to load.

**Expected behavior**
There should be no error dialogs.
<img width="577" alt="Screen Shot 2020-01-01 at 6 18 22 PM" src="https://user-images.githubusercontent.com/297151/71649427-8fbd1580-2cc3-11ea-9a56-eb64be634c74.png">

**Screenshots**

**Environment (please complete the following information):**

- OS: Mac OS

**Output from "Gradle Tasks"**
Gradle server started
Gradle client connecting to server...
Gradle server stopped
WebSocketClient: retry in 5000ms
WebSocketClient: reconnecting...
WebSocketClient: retry in 5000ms
ad infinitum

**Does the bug still exist if you disable all other extensions?**
Haven't checked yet

**Additional context**

**Comment by badsyntax** [comment]
Thanks for the bug report, and apologies introducing this issue. I'm having a bit of a hard time replicating this. 

Can you try execute the following in your terminal and let me know the output:

```bash
~/.vscode/extensions/richardwillis.vscode-gradle-2.4.2/lib/gradle-tasks 9999
```

**Comment by mativp** [comment]
I'm having the same issue please find below about output that you have asked.

```
(base) MacBook-Pro:extensions mativp$ ~/.vscode/extensions/richardwillis.vscode-gradle-2.4.2/lib/gradle-tasks 9999
Server started, waiting for clients
```


Please also check what gives VSC in the 'Gradle Tasks' output 

```
WebSocketClient: retry in 5000ms
WebSocketClient: reconnecting...
WebSocketClient: retry in 5000ms
Gradle server started
Gradle client connecting to server...
Gradle server stopped
WebSocketClient: retry in 5000ms
WebSocketClient: reconnecting...
WebSocketClient: retry in 5000ms
```

**Comment by badsyntax** [comment]
I've made a small change for better logging. Can you use version `2.4.3` and let me know the output of the "Gradle Server" task, for example:

<img width="899" alt="Screenshot 2020-01-02 at 13 33 04" src="https://user-images.githubusercontent.com/102141/71668311-ad908600-2d68-11ea-8e07-92fdde821770.png">

**Comment by zain-khatib** [comment]
I'm having the Exactly the same problem but with an exit code :1
with a Gradle Version 2.4.3
is there any solution to the problem

**Comment by badsyntax** [comment]
@zain-khatib please can you let me know the output or paste a screenshot of the "Gradle Server" task. Refer to my previous comment.

**Comment by jdavies** [comment]
Here is my Gradle Tasks output using v2.4.3:

> Executing task: ./gradle-tasks 54111 <

env: bash: No such file or directory
The terminal process terminated with exit code: 127

Terminal will be reused by tasks, press any key to close it.

> Executing task: ./gradle-tasks 54133 <

env: bash: No such file or directory
The terminal process terminated with exit code: 127

Terminal will be reused by tasks, press any key to close it.
<img width="1727" alt="Screen Shot 2020-01-02 at 8 44 52 PM" src="https://user-images.githubusercontent.com/297151/71707739-df254380-2da0-11ea-82eb-10bf07394106.png">

**Comment by zain-khatib** [comment]
![Capture](https://user-images.githubusercontent.com/59445850/71718166-015fa580-2e23-11ea-8289-805d2e85075b.PNG)
this is the my (Task-Gradle server) output

**Comment by badsyntax** [comment]
Thanks for the screenshots. Nothing obvious comes to mind. 

@jdavies can you run this and see if it runs correctly? 

```
~/.vscode/extensions/richardwillis.vscode-gradle-2.4.3/lib/gradle-tasks
```

Can you also let me know if you've added any custom terminal settings (eg terminal.integrated.shell.*)?

Can you also give me a file listing (using tree) of "~/.vscode/extensions/richardwillis.vscode-gradle-2.4.3"?

Without being able to replicate, I'm a little lost as to why this is erroring. I will add more logging to help diagnose this. 

Some other ideas I will try.

- manually escape the command with double quotes
- try ShellExecution instead of ProcessExecution

I just really wish I could replicate this problem. On a fresh vscode instance, on MacOS Catalina, there is no problem for me. 

If you're is aware of any customisations you've done or can help me with debugging this please let me know. Otherwise at this point it's gonna be an effort of trial and error with slow feedback loop.

**Comment by zain-khatib** [comment]
how can i test if these files work ??!
I'm trying to debug the problem step by step
![Capture2](https://user-images.githubusercontent.com/59445850/71731954-b5c2f100-2e4e-11ea-9a1d-8db36672066b.PNG)

**Comment by zain-khatib** [comment]
@badsyntax  I'm really sorry for confusing you that much ,  I forgot that you must install JAVA in order 
for the Gradle to work ,I downloaded JAVA and its all working good .my dearest apologies.

**Comment by badsyntax** [comment]
@zain-khatib no worries, it's good feedback, thanks for letting me know. I'll add a note about this to the README.

**Comment by jdavies** [comment]
@zain-khatib Here is the output of the command:

   ~/.vscode/extensions/richardwillis.vscode-gradle-2.4.3/lib/gradle-tasks
[WebSocketSelector-16] ERROR org.java_websocket.server.WebSocketServer - Shutdown due to fatal error
java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:461)
        at java.base/sun.nio.ch.Net.bind(Net.java:453)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:73)
        at org.java_websocket.server.WebSocketServer.doSetupSelectorAndServerThread(WebSocketServer.java:505)
        at org.java_websocket.server.WebSocketServer.run(WebSocketServer.java:315)
        at java.base/java.lang.Thread.run(Thread.java:834)

So it looks like a port is already in use. I went through my other extension and disabled the ones that I thought could be using a port (like LiveServer). till no luck. So I disabled all extensions and reloaded vscode. As soon as I enabled the Gradle Tasks extension, the error message appeared again.
<img width="2151" alt="Screen Shot 2020-01-03 at 10 43 44 AM" src="https://user-images.githubusercontent.com/297151/71742278-0f5af980-2e16-11ea-98a1-c2a00b9dec55.png">

Using the tree command I get the folloiwng:
   tree ~/.vscode/extensions/richardwillis.vscode-gradle-2.4.3
/Users/jdavies/.vscode/extensions/richardwillis.vscode-gradle-2.4.3
├── CHANGELOG.md
├── FEATURES.md
├── LICENSE.md
├── README.md
├── icon.png
├── lib
│   ├── gradle-tasks
│   ├── gradle-tasks-all.jar
│   └── gradle-tasks.bat
├── node_modules
│   ├── ansi-regex
│   │   ├── index.js
│   │   ├── license
│   │   ├── package.json
│   │   └── readme.md
│   ├── get-port
│   │   ├── index.js
│   │   ├── license
│   │   ├── package.json
│   │   └── readme.md
│   ├── strip-ansi
│   │   ├── index.js
│   │   ├── license
│   │   ├── package.json
│   │   └── readme.md
│   └── ws
│       ├── LICENSE
│       ├── README.md
│       ├── browser.js
│       ├── index.js
│       ├── lib
│       │   ├── buffer-util.js
│       │   ├── constants.js
│       │   ├── event-target.js
│       │   ├── extension.js
│       │   ├── limiter.js
│       │   ├── permessage-deflate.js
│       │   ├── receiver.js
│       │   ├── sender.js
│       │   ├── stream.js
│       │   ├── validation.js
│       │   ├── websocket-server.js
│       │   └── websocket.js
│       └── package.json
├── out
│   ├── client.js
│   ├── commands.js
│   ├── config.js
│   ├── extension.js
│   ├── gradleView.js
│   ├── server.js
│   └── tasks.js
├── package.json
├── resources
│   ├── dark
│   │   ├── add.svg
│   │   ├── gear.svg
│   │   ├── list-flat.svg
│   │   ├── list-tree.svg
│   │   ├── loading.svg
│   │   ├── refresh.svg
│   │   ├── run.svg
│   │   ├── script.svg
│   │   └── stop.svg
│   └── light
│       ├── add.svg
│       ├── gear.svg
│       ├── list-flat.svg
│       ├── list-tree.svg
│       ├── loading.svg
│       ├── refresh.svg
│       ├── run.svg
│       ├── script.svg
│       └── stop.svg
└── snippets
    ├── build.gradle.json
    └── build.gradle.kts.json

12 directories, 65 files

I hope that helps! Keep up the good work. I know how frustrating these kinds of things can be.

**Comment by badsyntax** [comment]
@jdavies Thanks for this info. I don't think this a port conflict issue as the extension will pass an open port as an argument to the gradle server: 

https://github.com/badsyntax/vscode-gradle/blob/b67ff79df2a3b1e9685543f297524d4cd95229b6/src/server.ts#L43

_(You can also see the extension passing an open port to the server command [in your screenshot](https://user-images.githubusercontent.com/297151/71707739-df254380-2da0-11ea-82eb-10bf07394106.png).)_

If you manually start the server without supplying a port argument (eg `./gradle-tasks`), it will use a default port and the port will only be freed some time after killing the server, and I think that's why you're seeing that exception. This doesn't appear to be happening in vscode as we'd see that same exception in the task terminal output. 

The error we're seeing in vscode is `env: bash: No such file or directory` when trying to execute the `gradle-tasks` shell script, and that error appears to be generated by the first line in that shell script, which is `#!/usr/bin/env bash`. This suggests a shell environment issue.

The server is started with a vscode task, using [`vscode.ProcessExecution`](https://code.visualstudio.com/api/references/vscode-api#ProcessExecution). Before I refactored things to use a long running server, I was using [`vscode.ShellExecution`](https://code.visualstudio.com/api/references/vscode-api#ShellExecution) to run gradle tasks. If this previously worked for you, then I will change the process execution to use `vscode.ShellExecution` instead of `vscode.ProcessExecution`. I've honestly struggled a bit to fully understand the differences, or why you're having this issue. I haven't been able to figure out much at looking at the vscode source code neither. I'll try get this change out today.

**Comment by badsyntax** [comment]
@jdavies i've changed how the server process is started with version `2.4.4`. Can you make sure you're using the latest version of the extension and see if it fixes things?

**Comment by mativp** [comment]
Hi, 

I'm still having problems but nows it refers to missing JAVA_HOME error even if it is set up correctly, please find screens below. 

<img width="1443" alt="Zrzut ekranu 2020-01-8 o 23 15 04" src="https://user-images.githubusercontent.com/25721390/72020839-f5357700-326c-11ea-8d2e-deca6c0013b4.png">


<img width="1032" alt="Zrzut ekranu 2020-01-8 o 23 16 32" src="https://user-images.githubusercontent.com/25721390/72020851-01213900-326d-11ea-8f8d-7aafdd9f7bf1.png">

@@EDIT 
I have forgot to write it, I'm able to run the script from terminal and it does works, issue occurs only in VSC

**Comment by jdavies** [comment]
> @jdavies i've changed how the server process is started with version `2.4.4`. Can you make sure you're using the latest version of the extension and see if it fixes things?

I'm still seeing the problem in 2.4.4. I have pressed the "Restart Server" button several times. If you need specific logs are configuration setting from my machine, just say the word. :)

<img width="1693" alt="Screen Shot 2020-01-09 at 10 43 08 AM" src="https://user-images.githubusercontent.com/297151/72095247-f5655f00-32cc-11ea-8405-c10136f0acde.png">

**Comment by badsyntax** [comment]
@jdavies can you update the extension to the latest version, then enable debug logging in the settings:

```json
{
    "gradle.debug": true
}
```

Then look at the output of "Gradle Tasks" in the output panel (note the first debug log):

<img width="1318" alt="Screenshot 2020-02-02 at 18 24 03" src="https://user-images.githubusercontent.com/102141/73612168-80462a80-45e9-11ea-80e1-bf936a30b6f4.png">

* Now within vscode, open a new terminal, then cd to the directoy listed in the logs above, and try to execute the server command with a random unused port.
* Also can you list the execute file so we can see the file permissions.

For example:

<img width="1301" alt="Screenshot 2020-02-02 at 18 27 54" src="https://user-images.githubusercontent.com/102141/73612194-d024f180-45e9-11ea-9f43-443841461e69.png">

Steps:

```
cd <your directory listed above>
./gradle-tasks 45454
ls -l gradle-tasks
```

I hope that makes sense. Thanks.

**Comment by badsyntax** [comment]
Woops sorry, didn't mean to close. I've made a change to how the server is started with #186. Can you make sure the extension is updated to `2.4.9` and see if the bug still exists?

**Comment by jdavies** [comment]
Same issue as before. I have attached a screenshot so you can see I am on 2.4.9.
<img width="1189" alt="Screen Shot 2020-02-13 at 2 59 06 PM" src="https://user-images.githubusercontent.com/297151/74486288-7df99100-4e71-11ea-8a0e-0a4fab40e94f.png">

I have not tried disabling all other extension yet. I'll report back when I get that done.

**Comment by stewi2** [comment]
I'm also having issues (on 2.4.9). Output in "Gradle Tasks":

```
[debug] Gradle Tasks Server dir: /Users/swill/.vscode/extensions/richardwillis.vscode-gradle-2.4.9/lib
[debug] Gradle Tasks Server cmd: "./gradle-tasks-server" 58759
[error] Error starting gradle server
[info] Gradle server stopped
```

but from a terminal window (in vscode itself):

```
$ cd /Users/swill/.vscode/extensions/richardwillis.vscode-gradle-2.4.9/lib
$ "./gradle-tasks-server" 58759
Server started, waiting for clients
```

I'm using MacOS Catalina btw.

**Comment by badsyntax** [comment]
Thanks for the feedback and your continued patience. Let's try a different approach. Can you create a `.vscode/tasks.json` with the following contents (but replace `/Users/richardwillis` with your home dir).

```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Start Gradle Server TEST",
      "type": "shell",
      "options": {
        "cwd": "/Users/richardwillis/.vscode/extensions/richardwillis.vscode-gradle-2.4.9/lib"
      },
      "args": ["1025"],
      "command": "\"./gradle-tasks-server\"",
      "problemMatcher": []
    }
  ]
}

```

Now run the task, by opening the command pallet, selecting `Run Task`, then selecting `Start Gradle Server TEST`, and let me if that errors out or not. Thanks.

**Comment by jdavies** [comment]
Hi Richard,   I have copied the error message here:
> > Executing task: "./gradle-tasks-server" 1025 <
> env: sh: No such file or directory
> The terminal process terminated with exit code: 127
> Terminal will be reused by tasks, press any key to close it.

Please let me know if I can help in anyway. This process just taught me a bit about tasks in VSCode, of which I was previously ignorant! :)

**Comment by badsyntax** [comment]
Thanks. Along the same lines, can you run this task and paste the output? 

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Print task shell info",
      "type": "shell",
      "command": "echo \"Path: $PATH \nShell: $SHELL\"",
      "problemMatcher": []
    }
  ]
}
```

**Comment by stewi2** [comment]
Looks like it doesn't include most of the path - probably because it doesn't run my .bash_profile first:

```
Path: /usr/gnu/bin:/usr/local/bin:/bin:/usr/bin:. 
Shell: /bin/bash
```

I also ran the above task, and it looks like vscode doesn't automatically set JAVA_HOME:

```
+ echo 'ERROR: JAVA_HOME is not set and no '\''java'\'' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.'
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
```

Although...

```
$ which java
/usr/bin/java
```

Which is in the path.

**Comment by jdavies** [comment]
I believe Stewi2 may be onto something. Here is my output:
```
Path: /Users/jdavies/development/flutter/bin:/Users/jdavies/development/flutter/bin/cache/dart-sdk/bin:/Users/jdavies/development/gradle-6.0.1/bin:~/development/apache-ant-1.10.7/bin 
Shell: /bin/zsh
```

However, in a normal terminal screen, here is my full path:
```
echo $PATH /Users/jdavies/bin:/opt/local/bin:/opt/local/sbin:/Users/jdavies/lbin:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/bin:/Users/jdavies/development/flutter/bin:/Users/jdavies/Library/Android/sdk/tools/bin:/Users/jdavies/Library/Android/sdk/platform-tools:/Users/jdavies/development/flutter/bin/cache/dart-sdk/bin:/Users/jdavies/development/gradle-6.0.1/bin:/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home:/Users/jdavies/nativescript-cli/bin:/usr/local/go/bin:/opt/X11/bin:/Library/Ballerina/ballerina-0.991.0/bin
```

My .bash_profile only contains a few entries:
```cat .bash_profile
[[ -s ~/.bashrc ]] && source ~/.bashrc

export PATH=/Users/jdavies/bin:$PATH

[[ -e "/Users/jdavies/lib/oracle-cli/lib/python2.7/site-packages/oci_cli/bin/oci_autocomplete.sh" ]] && source "/Users/jdavies/lib/oracle-cli/lib/python2.7/site-packages/oci_cli/bin/oci_autocomplete.sh"

[[ -e "/Users/jdavies/lib/oracle-cli/lib/python3.8/site-packages/oci_cli/bin/oci_autocomplete.sh" ]] && source "/Users/jdavies/lib/oracle-cli/lib/python3.8/site-packages/oci_cli/bin/oci_autocomplete.sh"
```

Where as as my .bashrc contains the lion's share of the PATH elements.
```
export ANDROID_HOME=/Users/jdavies/Library/Android/sdk
export FLUTTER_HOME=/Users/jdavies/development/flutter
export GRADLE_HOME=/Users/jdavies/development/gradle-6.0.1
export DART_HOME=$FLUTTER_HOME/bin/cache/dart-sdk
### export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home
export CLASSPATH=/Users/home/jdavies/development/commons-net-3.6/commons-net-3.6.jar:$ANDROID_HOME/tools/lib
```

**Comment by jdavies** [comment]
Doing a quick search on VSCode PATH isues led me to (as usual) StackOverflow: https://stackoverflow.com/questions/51820921/vscode-integrated-terminal-doesnt-load-bashrc-or-bash-profile

I edited my settings file in VSCode directly setting the PATH argument in the Osx section to the full path recognized by my systems terminal:

```
"terminal.integrated.env.osx": {
        "PATH": "/Users/jdavies/bin:/opt/local/bin:/opt/local/sbin:/Users/jdavies/lbin:/Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/bin:/Users/jdavies/development/flutter/bin:/Users/jdavies/Library/Android/sdk/tools/bin:/Users/jdavies/Library/Android/sdk/platform-tools:/Users/jdavies/development/flutter/bin/cache/dart-sdk/bin:/Users/jdavies/development/gradle-6.0.1/bin:/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home:/Users/jdavies/nativescript-cli/bin:/usr/local/go/bin:/opt/X11/bin:/Library/Ballerina/ballerina-0.991.0/bin",
        "CLASSPATH": "/Users/home/jdavies/development/commons-net-3.6/commons-net-3.6.jar:/Users/home/jdavies/development/apache-ant-1.10.7/lib/ant-apache-oro.jar:/Users/home/jdavies/development/apache-ant-1.10.7/lib/ant-commons-net.jar"
    },
```

I restarted VSCode and the error no longer appears. Woo hoo!

EDIT: Looking at my PATH variable reminds me I have some system housekeeping to do!

**Comment by badsyntax** [comment]
@jdavies that's definitely the source of the problem! good find. i'm not sure why your $PATH is not correct, but you're missing `/usr/bin` and this is why the script was failing. glad you found a solution to this :)

**Comment by badsyntax** [comment]
@stewi2 the extension relies on java being setup correctly. are you able to run `./gradlew tasks` in your project?

**Comment by badsyntax** [comment]
I've captured some information on how to debug issues this like in the  [troubleshooting](https://github.com/badsyntax/vscode-gradle/blob/master/README.md#troubleshooting) section in the README (see "No connection to the gradle server. Try restarting the server"). 
As there's not anything further I can do, I'm closing this issue now. 🎉

**Comment by emeentag** [comment]
Hi i fix that issue by changing my java version anything up to `v11`. Because my project is pointed to `v11` but in my windows machine `JAVA_HOME` is set to 8. So i think these needs to be aligned. So i changed my `JAVA_HOME` to a version to `v11`. Hope that helps. By the way in windows 10 `JAVA_HOME` needs to be end with out `;`. 
I have to use windows at my work and i am spending a good amount of time to satisfy that OS for getting to be ready to develop sth :)
