### ISSUE TITLE
[Question] Building the extension locally

### ISSUE THREAD

**Issue by gayanper** [microsoft/vscode-gradle#1401]
I'm trying to build extension locally to test some changes with my daily work. But with new build-server changes I don't see there this folder `build-server-for-gradle` is coming from. There seems to be references in azure pipeline, but not sure where this artifacts gets build and where the source code is. Can you provide some steps how to build the extension locally with new build-server changes ?

**Comment by gayanper** [comment]
@testforstephen @Eskibear @CsCherrYY @jdneo Please let me know if the artifacts can be downloaded from some where.

**Comment by jdneo** [comment]
Ah, sorry @gayanper that currently the repo 'build-server-for-gradle' is not open-sourced yet. (We will make it public in near future)

Which part did you change? If it's not related to build server, you can just ignore it.

**Comment by gayanper** [comment]
@jdneo it's the PR I have opened for nested closure completions for this repo. Now I could copy the bs files from the official extension files as a workaround. But another suggestion is could me put those bs files in a Azure Artifacts ?

**Comment by jdneo** [comment]
The gradle build server is open source now. Please refer to CONTRIBUTING.md for more details :)
