### ISSUE TITLE
mo

### ISSUE THREAD

**Issue by MohameHassan139** [microsoft/vscode-gradle#1408]
Extension Name: vscode-gradle
Extension Version:
OS Version:
VSCode version:

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Output from "Gradle for Java"**
You can find this by clicking on the "Output" panel, then selecting the "Gradle for Java" channel from the dropdown.

**Does the bug still exist if you disable all other extensions?**
Yes/No

**Additional context**

**Comment by jdneo** [comment]
Please provide details, thanks.
