### ISSUE TITLE
gradle project with sub projects does not integrate properly with test runner

### ISSUE THREAD

**Issue by robaho** [microsoft/vscode-gradle#1417]
Extension Name: vscode-gradle
Extension Version: 3.12.7
OS Version: linux
VSCode version: 1.82.2

When using gradle with subprojects, the vscode 'testing explorer' does not set the working directory to the top of the subproject when running tests in the project.

Using the gradle extension 'GRADLE PROJECTS', I see all of the projects, and can successfully run the tests from there.

**Comment by jdneo** [comment]
Tracked by https://github.com/microsoft/vscode-java-test/issues/1606
