### ISSUE TITLE
[dev] Extension dependency grpc-tools v1.12.x does not work on Windows

### ISSUE THREAD

**Issue by JoseLion** [microsoft/vscode-gradle#1428]
Extension Name: vscode-gradle
Extension Version: v3.12.7
OS Version: Windows 11 22H2 (build 22621.2361)
VSCode version: v1.83.0

**Describe the bug**
As described in https://github.com/grpc/grpc-node/issues/2338, it seems that any version of `grpc-tools` greater or equal to `v1.12.0` is broken on Windows. However, it is possible to fix the problem by installing VS 2022 C++ build tools and Windows Universal CRT SDK. I think there could be two options to solve this issue:
1. Revert the `grpc-tools` version to the latest v1.11.x
2. Add the build tools requirements for Windows to the CONTRIBUTING.md documentation

I'll be glad to help out with a PR for this, so please let me know which one of the options above would be the best fit for the project 🙂 

**To Reproduce**
1. Use Windows machine
2. Run `./gradlew build` to build the project
4. Build fails on the grcp protoc execution

**Expected behavior**
Build should also work on Windows

**Screenshots**
N/A

**Output from "Gradle for Java"**
N/A

**Does the bug still exist if you disable all other extensions?**
N/A

**Additional context**
Build error output:
```shell
> Task :extension:npmInstall
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'vscode-gradle@3.13.0',
npm WARN EBADENGINE   required: { vscode: '^1.76.0', node: '^14.15.4', npm: '^6.14.10' },
npm WARN EBADENGINE   current: { node: 'v18.18.0', npm: '9.8.1' }
npm WARN EBADENGINE }

added 505 packages, and audited 506 packages in 11s

87 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> Task :extension:generateProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':extension:generateProto'.
> protoc: stdout: . stderr: C:\Repos\vscode-gradle\extension\node_modules\grpc-tools\bin\protoc_plugin.js:37
      throw error;
      ^

  Error: Command failed: C:\Repos\vscode-gradle\extension\node_modules\grpc-tools\bin\grpc_node_plugin.exe

      at ChildProcess.exithandler (node:child_process:422:12)
      at ChildProcess.emit (node:events:517:28)
      at maybeClose (node:internal/child_process:1098:16)
      at ChildProcess._handle.onexit (node:internal/child_process:303:5) {
    code: 3221225781,
    killed: false,
    signal: null,
    cmd: 'C:\\Repos\\vscode-gradle\\extension\\node_modules\\grpc-tools\\bin\\grpc_node_plugin.exe'
  }

  Node.js v18.18.0
  --grpc_out: protoc-gen-grpc: Plugin failed with status code 1.


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.4/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 32s
14 actionable tasks: 14 executed
```

**Comment by jdneo** [comment]
Thank you @JoseLion

I prefer `2. Add the build tools requirements for Windows to the CONTRIBUTING.md documentation`. Keep the dependencies up to date could avoid any potential vulnerability issues.

**Comment by JoseLion** [comment]
@jdneo I agree! It's better to keep the dependencies up-to-date. I like option `2.` better as well. I'll open a PR with those changes later today 🙂
