### ISSUE TITLE
Can we use this with gradle 6.5 and run using Jenkins 

### ISSUE THREAD

**Issue by Dhruva23** [microsoft/vscode-gradle#1446]

**Comment by jdneo** [comment]
You can use gradle 6.5 as long as you have right JDK to launch the daemon. And set it to `java.import.gradle.java.home` in the `WORKSPACE` setting scope

See: https://docs.gradle.org/current/userguide/compatibility.html

> run using Jenkins

Can you provide more details about this?

**Comment by Dhruva23** [comment]
Hi, I assumption is that, we are using visual studio client in local machine, with this plugin, we can run bdd tasks in parallel, if we check in the code to git hub, does Jenkins need this plugin as well to run tasks in parallel

**Comment by jdneo** [comment]
This extension has nothing to do with Jenkins. I guess you are running gradle tasks via command line in Jenkins. You should check if Gradle support parallel execution from command line.
