### ISSUE TITLE
Gradle Icon not appearing in activity bar

### ISSUE THREAD

**Issue by jdreddaway** [microsoft/vscode-gradle#1453]
Extension Name: vscode-gradle
Extension Version: v3.13.4
OS Version: Windows 11
VSCode version: 1.84.2

**Describe the bug**
Gradle icon not showing up in activity bar.

**To Reproduce**

1. Create a Gradle project in IntelliJ.
2. Open the project's parent folder in VSCode
3. Install the Gradle Extension

**Expected behavior**
I see the extension in the activity bar.

**Screenshots**

<img width="1247" alt="image" src="https://github.com/microsoft/vscode-gradle/assets/8442177/49d6e1d3-c847-44c7-94a2-6e9252e4d48e">

**Output from "Gradle for Java"**

none

**Does the bug still exist if you disable all other extensions?**
Yes/No

**Additional context**

**Comment by binsim** [comment]
As far as I understand the working of VS Code, you have to open VS Code in __OptionsProbatilitiesKt__ folder not in __STOCKOPTIONS__. This extension checks for the _gradlew-files_ at the root level of the project and not recursively.

**Comment by jdneo** [comment]
Thank you @binsim for the answer. And if you want to activate the extension for this kind of 'nested' project, please considering using this setting: `gradle.nestedProjects`
