### ISSUE TITLE
how to disable .project file update when open vscode with a java project previously created in eclipse.

### ISSUE THREAD

**Issue by d95776** [microsoft/vscode-gradle#1454]
how to disable .project file update when open vscode with a java project previously created in eclipse.

**Comment by jdneo** [comment]
Hi @d95776 

Sorry it's an unresolved issue from upstream: https://github.com/redhat-developer/vscode-java/issues/2741.

AFAIK, currently as long as the project is imported by the java extension, there is no way to avoid this.
