### ISSUE TITLE
创建java项目不要下载gradle

### ISSUE THREAD

**Issue by ncnnnnn** [microsoft/vscode-gradle#1471]
**Is your feature request related to a problem? Please describe.**

```
  "java.import.gradle.home": "。。",
  "java.import.gradle.version": "8.0.2",
  "java.import.gradle.java.home": "。。",
  "java.import.gradle.wrapper.enabled": false
```
这些设置一点用都没有。
每次还是 

···
Downloading from https://services.gradle.org/distributions/gradle-8.0.2-bin.zip
···

还不如直接终端里面 gradle.bat init还省事多了，，，

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SaikaAn** [comment]
我是阅读了 com.github.badsyntax.gradle.GradleProjectConnector#setConnectorConfig 这个函数里面的逻辑解决的：
  仅仅只配置下面两个
  "java.import.gradle.home": "{your path}",
    "java.import.gradle.wrapper.enabled": false,
其他的配置项都删除掉了
务必保证  "java.import.gradle.version"的值为空 ，不要去配置它

**Comment by ncnnnnn** [comment]
谢谢。非常有效。
