### ISSUE TITLE
connecting srivece error

### ISSUE THREAD

**Issue by 712236276** [microsoft/vscode-gradle#1477]
Extension Name: vscode-gradle
Extension Version:
OS Version:
VSCode version:

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Output from "Gradle for Java"**
You can find this by clicking on the "Output" panel, then selecting the "Gradle for Java" channel from the dropdown.

**Does the bug still exist if you disable all other extensions?**
Yes/No

**Additional context**

**Comment by jdneo** [comment]
Please provide more details, thanks!
