### ISSUE TITLE
conflicts with java language extension pack

### ISSUE THREAD

**Issue by Arteiimis** [microsoft/vscode-gradle#1513]
Extension Name: vscode-gradle
Extension Version:
OS Version:
VSCode version:

**Describe the bug**
after installing both gradle and java extension pack, creating a new springboot project will cause the java status log to keep downloading packages

**To Reproduce**
- Install java extension pack and gradle for java.
- Create a new springboot gradl project with all configuration options as default.
- Open the created project, open the java status will show that the package is always being installed.

**Expected behavior**
No conflict with any plugin, load the whole project normally.

**Output from "Gradle for Java"**
```
[info] [gradle-server] Server started, listening on 53512
[info] Gradle client connected to server
[info] Found 0 tasks
[info] Java Home: D:\scoop\apps\openjdk17\current
[info] JVM Args: --add-opens=java.base/java.util=ALL-UNNAMED,--add-opens=java.base/java.lang=ALL-UNNAMED,--add-opens=java.base/java.lang.invoke=ALL-UNNAMED,--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens=java.base/java.nio.charset=ALL-UNNAMED,--add-opens=java.base/java.net=ALL-UNNAMED,--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED,-XX:MaxMetaspaceSize=384m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=CN,-Duser.language=zh,-Duser.variant
[info] Gradle User Home: D:\scoop\apps\gradle\current\.gradle
[info] Gradle Version: 8.8
[info] Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.8/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

CONFIGURE SUCCESSFUL in 20s
```
It will not show any errors in the output of gradle, but it will download indefinitely in java build status:
![image](https://github.com/microsoft/vscode-gradle/assets/94288976/2d8cdbab-2f52-46ec-9ffe-df0301cefe09)

**Does the bug still exist if you disable all other extensions?**
just disable gradle extension, the entire project will not have any problems

**Comment by jdneo** [comment]
Is the download jar always the same one, or it's changing?

**Comment by Arteiimis** [comment]
> Is the download jar always the same one, or it's changing?

will change, but it seems to never finish downloading, this morning I put the laptop aside to download for three hours, and still did not finish downloading, my network everything is normal, and after installing the gradle plugin java build status output will be different, will become like the screenshot of the beginning of the null information, while the normal situation is eight hexadecimal numbers

**Comment by jdneo** [comment]
You can turn off setting `java.gradle.buildServer.enabled`.

I'll check why it's so slow. Just new springboot problem with default options right?

**Comment by Arteiimis** [comment]
> You can turn off setting `java.gradle.buildServer.enabled`.
> 
> I'll check why it's so slow. Just new springboot problem with default options right?

Yes, all settings are default, just select the springboot web dependency.

**Comment by codespearhead** [comment]
I cannot reproduce the issue on my end.

I looked into your profile and it seems that you're from China, so I suggest adding [these mirrors](https://github.com/china-speed/china-speed.github.io?tab=readme-ov-file#gradle-maven) and trying again.

**Comment by Arteiimis** [comment]
> I cannot reproduce the issue on my end.
> 
> I looked into your profile and it seems that you're from China, so I suggest adding [these mirrors](https://github.com/china-speed/china-speed.github.io?tab=readme-ov-file#gradle-maven) and trying again.

thanks a lot! i'll try it!
