### ISSUE TITLE
The Gradle client was unable to connect

### ISSUE THREAD

**Issue by neoacevedo** [microsoft/vscode-gradle#1535]
Extension Name: vscode-gradle
Extension Version: 3.15.0
OS Version: openSUSE Tumbleweed
VSCode version:  1.91.1

**Describe the bug**
It's just like https://github.com/microsoft/vscode-gradle/issues/1310 and https://github.com/microsoft/vscode-gradle/issues/1221

**Comment by jdneo** [comment]
Could you provide more details, e.g. screenshots, log, etc..?

**Comment by shindeyy** [comment]
Getting below error, Not able to run the flutter application.
<img width="502" alt="Screenshot 2024-08-03 at 9 41 25 AM" src="https://github.com/user-attachments/assets/0f177966-2d2f-41f5-b3ad-89fbe6752406">

**Comment by jdneo** [comment]
Please see if https://github.com/microsoft/vscode-gradle/issues/1546#issuecomment-2265157657 can solve it.

**Comment by neoacevedo** [comment]
Today the extension was updated, then I reloaded the IDE and I didn't see the error.
