### ISSUE TITLE
FAILURE Problem with no info.

### ISSUE THREAD

**Issue by dailytabs** [microsoft/vscode-gradle#1559]
Upgraded using wrapper to 8.9.

Everything works perfectly fine, but now I always show a Problem:
- FAILURE
```
Build failed with an exception. [Ln 1, Col 1]
```
Other bugs indicate this is a version mismatch. I only have gradle and the VS code gradle plugin, so I assume this is your problem?

**Maybe Related:**
The first line of my build.gradle has been showing a Problem:
- build.gradle
```
Could not run phased build action using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-8.9-all.zip'.
The specified initialization script '/home/user/.vscode-server/data/User/globalStorage/redhat.java/1.32.0/config_linux/org.eclipse.osgi/55/0/.cp/gradle/init/init.gradle' does not exist.
```

![image](https://github.com/user-attachments/assets/645e1a8a-57ec-462b-b2e3-f87c28ac189a)

I am currently using 1.33.0, which does have the file. When I downgrade to 1.32.0, the dir is there, but the file does not exist.
Even if the file existed in both, why is it using an old java plugin when I don't use that one?

**ICIM:**
I changed `plugins { id 'groovy' ...` to `plugins { id 'java' ...` around the same time, as I had switched to java-only a long time ago and forgot to update it here.

**Comment by dailytabs** [comment]
![image](https://github.com/user-attachments/assets/645e1a8a-57ec-462b-b2e3-f87c28ac189a)

**Comment by jdneo** [comment]
It's caused by the `redhat.java` extension. As you can tell that from the path component.

Anyway,

Did you installed the `Gradle for Java` extension? If yes, will this issue get solved if you trigger `Java: Clean Java Language Server Workspace`
