### ISSUE TITLE
Gradle Kotlin (Spring Boot) - languageVersion = JavaLanguageVersion.of(22) - Not working

### ISSUE THREAD

**Issue by drakgoku** [microsoft/vscode-gradle#1588]
### Current Behavior

```
java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(22)
	}
}
```
```
Produces:

[info] Java Home: C:\Users\.........\.vscode\extensions\redhat.java-1.33.0-win32-x64\jre\17.0.11-win32-x86_64
[info] JVM Args: --add-opens=java.base/java.util=ALL-UNNAMED,--add-opens=java.base/java.lang=ALL-UNNAMED,--add-opens=java.base/java.lang.invoke=ALL-UNNAMED,--add-opens=java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens=java.base/java.nio.charset=ALL-UNNAMED,--add-opens=java.base/java.net=ALL-UNNAMED,--add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED,-XX:MaxMetaspaceSize=384m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=ES,-Duser.language=es,-Duser.variant
[info] Gradle User Home: C:\Users\..........\.gradle
[info] Gradle Version: 8.8
[error] FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
   > Cannot find a Java installation on your machine matching this tasks requirements: {languageVersion=22, vendor=any, implementation=vendor-specific} for WINDOWS on x86_64.
      > No locally installed toolchains match and toolchain download repositories have not been configured.

* Try:
> Learn more about toolchain auto-detection at https://docs.gradle.org/8.8/userguide/toolchains.html#sec:auto_detection.
> Learn more about toolchain repositories at https://docs.gradle.org/8.8/userguide/toolchains.html#sub:download_repositories.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

CONFIGURE FAILED in 1s
[error] [gradle-server] The supplied build action failed with an exception.
[error] Error getting build for d:\.................. The supplied build action failed with an exception.
[info] Found 0 tasks
```

### Expected Behavior

```
java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}
```

CONFIGURE SUCCESSFUL in 1s
[info] Found 40 tasks

### Steps to Reproduce

1. Download the project at https://start.spring.io/
>1. Version project Spring Boot: 3.3.2
>2. Language: Java
>3. Java version: 22
>4. Gradle kotlin == Gradle kotlin dsl
2. From VSC you modify something or simply update and it gives an error in version 22
languageVersion = JavaLanguageVersion.of(22)

### Gradle version

https://start.spring.io/ - 3.3.2 spring boot

### Environment 

Windows

JAVA_HOME => D:\...........\Java\jdk-22.0.1

![image](https://github.com/user-attachments/assets/943e4498-ef80-41fd-82ee-583659c8f26f)

> **Note**: The Spring Boot parent project does not seem to be able to have version 22. But the Spring Boot modules/microservices/child projects can. But once the parent includes them with: include("module1, module n+1) the modules/microservices/children can no longer have version 22.
> 
> So we have:
> - SpringBoot parent: cannot have version 22 but can have version 21
> - - SpringBoot module/microservice/child: can have version 22
>
> When the parent links with include("child/microservice/child") then the child cannot have version 22 and we are left with
> - SpringBoot parent: version 21
> - - SpringBoot module/microservice/child: version 21
> 
> If you try another version it will give an error.
> 

https://github.com/gradle/gradle/issues/30214

**Comment by Arthurm1** [comment]
I could be wrong but I'm guessing if you run `gradlew -q javaToolchains` then you'll get your `jdk-22` listed with `Detected by: Current JVM` and that's the only way Gradle is detecting JDK22 and so compiling from the CLI.

From your logs, the VSCode extension is using `C:\Users\.........\.vscode\extensions\redhat.java-1.33.0-win32-x64\jre\17.0.11-win32-x86_64` to run Gradle so it can no longer find the JDK22 as it's not the current JVM.

You could setup toolchain detection properly on your machine.  Then Gradle should be able to find JDK22 regardless of what JDK is being used to run Gradle.  That is suggested in the Gradle error message you've pasted and the weblinks are given.

Or you could try adding the VSCode setting `"java.import.gradle.java.home": "D:\\your path here\\Java\\jdk-22.0.1"`.  Then the extension should run Gradle with that JDK and JDK22 should be found as a toolchain.

**Comment by jdneo** [comment]
The Java Home `C:\Users\.........\.vscode\extensions\redhat.java-1.33.0-win32-x64\jre\17.0.11-win32-x86_64` is used to launch the gradle server (the server providing all the related gradle features)

And the gradle daemon should have the capability to detect the jdk it needs. Where is your jdk 22 installed? I opened this project in my machine and cannot reproduce it

![image](https://github.com/user-attachments/assets/1133a3bf-b6e4-4a1f-b030-90def4b15e69)

**Comment by drakgoku** [comment]
This is my gradle:

[plugins {
	java
	id("org.springframework.boot") version "3.3.3"
	id("io.spring.dependency-management") version "1.1.6"
}

group = "com.........."
version = "0.0.1-SNAPSHOT"

// java {
// 	toolchain {
// 		languageVersion = JavaLanguageVersion.of(21)
// 	}
// }

repositories {
	mavenCentral()
}

dependencies {
	implementation("org.springframework.boot:spring-boot-starter")
	testImplementation("org.springframework.boot:spring-boot-starter-test")
	testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// tasks.withType<Test> {
// 	useJUnitPlatform()
// }

subprojects{
    apply(plugin="java")
    apply(plugin="org.springframework.boot")
    apply(plugin="io.spring.dependency-management")


    group = "com.wammo"
    version = "0.0.1-SNAPSHOT"

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(22)
        }
    }
    configurations {
        compileOnly {
            extendsFrom(configurations.annotationProcessor.get())
        }
    }
    repositories {
        mavenCentral()
    }

    dependencies {

        implementation("org.springframework.boot:spring-boot-starter-web")
        testImplementation("org.springframework.boot:spring-boot-starter-test")

        // implementation("org.springframework.boot:spring-boot-starter-security")
        // testImplementation("org.springframework.security:spring-security-test")

        developmentOnly("org.springframework.boot:spring-boot-devtools")

        compileOnly("org.projectlombok:lombok")
        annotationProcessor("org.projectlombok:lombok")
        
    }

     tasks.withType<JavaCompile>().configureEach {

        options.compilerArgs.add("-parameters")
    }


    // En las pruebas de integración necesitan los parámetros.



    // tasks.withType<Test> {
    //     useJUnitPlatform()
    // }
}](url)
This is my gradle, with multiple microservices.
I have it in modules because if I have to update any dependency I do it in cascade instead of going project by project and wasting time.

I have downloaded the project again from spring boot init and it is still the same.
![image](https://github.com/user-attachments/assets/fc4189da-7c31-4b1e-a32d-0cb45beef9a7)

![image](https://github.com/user-attachments/assets/05f6441b-02ad-4c1b-b603-4af04f1aca66)

gradlew -q javaToolchains:
![image](https://github.com/user-attachments/assets/98ef88df-f331-475d-b729-f1de27f225c5)

It does detect version 22. But it's like it doesn't want to detect it.

![image](https://github.com/user-attachments/assets/9f160331-0947-42b1-961d-e9b4a525179e)

**Comment by drakgoku** [comment]
This is my gradle:

```
plugins {
    java
    id("org.springframework.boot") version "3.3.3"
    id("io.spring.dependency-management") version "1.1.6"
}

group = "com......"

version = "0.0.1-SNAPSHOT"

java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }

repositories { mavenCentral() }

dependencies {
    implementation("org.springframework.boot:spring-boot-starter")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// tasks.withType<Test> {
// 	useJUnitPlatform()
// }

subprojects {
    apply(plugin = "java")
    apply(plugin = "org.springframework.boot")
    apply(plugin = "io.spring.dependency-management")

    group = "com......"
    version = "0.0.1-SNAPSHOT"

    java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }
    configurations { compileOnly { extendsFrom(configurations.annotationProcessor.get()) } }
    repositories { mavenCentral() }

    dependencies {
        implementation("org.springframework.boot:spring-boot-starter-web")
        testImplementation("org.springframework.boot:spring-boot-starter-test")

        // implementation("org.springframework.boot:spring-boot-starter-security")
        // testImplementation("org.springframework.security:spring-security-test")

        developmentOnly("org.springframework.boot:spring-boot-devtools")

        compileOnly("org.projectlombok:lombok")
        annotationProcessor("org.projectlombok:lombok")
    }

    tasks.withType<JavaCompile>().configureEach { options.compilerArgs.add("-parameters") }

    // En las pruebas de integración necesitan los parámetros.

    // tasks.withType<Test> {
    //     useJUnitPlatform()
    // }
}

```

This is my gradle, with multiple microservices.
I have it in modules because if I have to update any dependency I do it in cascade instead of going project by project and wasting time.

I have downloaded the project again from spring boot init and it is still the same.
![image](https://github.com/user-attachments/assets/fc4189da-7c31-4b1e-a32d-0cb45beef9a7)

![image](https://github.com/user-attachments/assets/05f6441b-02ad-4c1b-b603-4af04f1aca66)

gradlew -q javaToolchains:
![image](https://github.com/user-attachments/assets/98ef88df-f331-475d-b729-f1de27f225c5)

It does detect version 22. But it's like it doesn't want to detect it.

![image](https://github.com/user-attachments/assets/9f160331-0947-42b1-961d-e9b4a525179e)

**Comment by drakgoku** [comment]
This is my gradle:

```
plugins {
	java
	id("org.springframework.boot") version "3.3.3"
	id("io.spring.dependency-management") version "1.1.6"
}

group = "com......"
version = "0.0.1-SNAPSHOT"

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation("org.springframework.boot:spring-boot-starter")
	testImplementation("org.springframework.boot:spring-boot-starter-test")
	testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// tasks.withType<Test> {
// 	useJUnitPlatform()
// }

subprojects{
    apply(plugin="java")
    apply(plugin="org.springframework.boot")
    apply(plugin="io.spring.dependency-management")


    group = "com........"
    version = "0.0.1-SNAPSHOT"

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }
    configurations {
        compileOnly {
            extendsFrom(configurations.annotationProcessor.get())
        }
    }
    repositories {
        mavenCentral()
    }

    dependencies {

        implementation("org.springframework.boot:spring-boot-starter-web")
        testImplementation("org.springframework.boot:spring-boot-starter-test")

        // implementation("org.springframework.boot:spring-boot-starter-security")
        // testImplementation("org.springframework.security:spring-security-test")

        developmentOnly("org.springframework.boot:spring-boot-devtools")

        compileOnly("org.projectlombok:lombok")
        annotationProcessor("org.projectlombok:lombok")
        
    }

     tasks.withType<JavaCompile>().configureEach {

        options.compilerArgs.add("-parameters")
    }


    // En las pruebas de integración necesitan los parámetros.



    // tasks.withType<Test> {
    //     useJUnitPlatform()
    // }
}

```

This is my gradle, with multiple microservices.
I have it in modules because if I have to update any dependency I do it in cascade instead of going project by project and wasting time. Then each project will have its specific dependencies apart from the Java version itself, some dependencies, tests and others...

I have downloaded the project again from spring boot init and it is still the same.
![image](https://github.com/user-attachments/assets/30e5a9cb-4911-4e9b-a32a-2ddc92caa057)

![image](https://github.com/user-attachments/assets/262d7da9-e93d-4934-a946-52cb73eaaa5a)


`**gradlew -q javaToolchains:**`

![image](https://github.com/user-attachments/assets/05a1abdd-8454-4fcc-ac23-b40aa2f5d0b1)

It does detect version 22. But it's like it doesn't want to detect it.

![image](https://github.com/user-attachments/assets/992a31df-0bf7-43d8-b3ad-6f7bb013d3c5)

**Comment by jdneo** [comment]
Have you tried set `java.import.gradle.java.home` to java 22?

**Comment by drakgoku** [comment]
Yes I am using it. But it's no use.
![image](https://github.com/user-attachments/assets/46a47b2a-fb51-44fa-be1f-6b154265045c)

It seems like something internal, like it's only picking up their versions of .gradle\jdks\... and not mine.

**Comment by jdneo** [comment]
You missed the "java" part.

It's `java.import.gradle.java.home` not `java.import.gradle.home`

:)

**Comment by drakgoku** [comment]
You are right. It seems to be working fine now. Thank you very much. That fixes the problem. 
Why do you have to manually tell it? Doesn't it detect it automatically with my environment variable?

**Comment by jdneo** [comment]
I do not have a concrete answer for now. Sometime the gradle cli behavior may different from the gradle tooling api. But it also may related with the implementation of the gradle task server in this extension.

Anyway, good to know the issue is addressed.
