### ISSUE TITLE
sub projects belong to wrong folder in explorer

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode-gradle#1614]
I found an issue about this change that some of the modules are in the wrong place:

![image](https://github.com/user-attachments/assets/f4ec785b-e6d8-4830-988f-b100ccee0379)

For example, here: the `app` and `mylibrary` should belong to `android-test`.

Clone and open the project https://github.com/microsoft/build-server-for-gradle can reproduce the error

_Originally posted by @jdneo in https://github.com/microsoft/vscode-gradle/issues/1612#issuecomment-2401103641_

**Comment by jjohannes** [comment]
@jdneo I will have a look at this and provide a fix.

**Comment by jjohannes** [comment]
@jdneo I was ignoring the option `gradle.nestedProjects: true` and did not test with it. With this option in mind, it is clear to me why my solution causes this issue. I provided a fix here: #1617

I was also surprised why it does not show more builds/projects for the https://github.com/microsoft/build-server-for-gradle repository, which I think it should. Here is a proposal to change that: #1618

**Comment by jdneo** [comment]
Thank you! I'll look at them ASAP.
