### ISSUE TITLE
Does this extension support debugging in VSCode?

### ISSUE THREAD

**Issue by pdubb29** [microsoft/vscode-gradle#239]
This is a fantastic extension. I'm so excited to use this in VSCode! Thanks for your hard work on this.

As the title suggests, this is a question, and not an issue.

**Comment by pdubb29** [comment]
Nevermind, we don't need this feature, as there is already a debugger for Java extension.

**Comment by badsyntax** [comment]
Hey. Thanks for the feedback. Just trying to understand your original request a bit better. Would have liked to debug Java code when running your app via a gradle task?

**Comment by pdubb29** [comment]
Correct, it works when you use the java debugger with a launch.json file.

**Comment by badsyntax** [comment]
Refs https://github.com/badsyntax/vscode-gradle/issues/244

**Comment by badsyntax** [comment]
This feature is now released with version [2.7.0](https://github.com/badsyntax/vscode-gradle/releases/tag/2.7.0). Can you update and give it a go? Let me know if there are any issues. 
Refer to the README for instructions on how to use this feature: https://github.com/badsyntax/vscode-gradle#debugging-javaexec-tasks
Thanks!

**Comment by pdubb29** [comment]
Yeah I'll check it out!

**Comment by pdubb29** [comment]
This works great! Thanks for keeping me up to date!
