### ISSUE TITLE
Cannot run task on Win when using Bash as default terminal

### ISSUE THREAD

**Issue by HerrDerb** [microsoft/vscode-gradle#24]
I use VSC on Windows 10 and configured the git bash as default terminal. 

As a task gets executed by the extension as  `c:\ieu\development\myProject\gradlew.bat tasks` in the bash terminal, it results in a effective call of 
`/usr/bin/bash: c:ieumyProjectgradlew.bat task`  which obviously results in a failure.

1. Allow a different terminal for the extension to execute the tasks
2. Avoid accidental escaping of chars in a unix terminal when passing a windows path

**Comment by badsyntax** [comment]
Thanks for this report, I've been able to reproduce. It would be best if the extension could handle running the gradlew wrapper executable in different environments without having the user to explicitly set paths & shells. Git Bash on Windows is a tricky one. I'm looking into fixing this.

Also I wonder if you have any advice, as to which executable is better to run on Git Bash on Windows? `gradlew` or `gradlew.bat`? Both seem to run fine, just not sure which the better option for this environment.

**Comment by badsyntax** [comment]
This should be fixed with version `2.1.1`, which should be available in the next few mins. Let me know if the problem persists.

**Comment by HerrDerb** [comment]
Looking good. Thanks for the quick intervention :)

**Comment by badsyntax** [comment]
Great, thanks for letting me know.
