### ISSUE TITLE
No gradle tasks show up from me

### ISSUE THREAD

**Issue by AceHack** [microsoft/vscode-gradle#253]
Extension Name: vscode-gradle
Extension Version: latest
OS Version: Mac
VSCode version: latest stable

**Describe the bug**
No gradle tasks show up for me.  I can see them under tasks explorer but not gradle tasks

**To Reproduce**
Open java project.

**Expected behavior**
Gradle tasks to show up.

**Screenshots**
![image](https://user-images.githubusercontent.com/578953/78391217-f0eed080-75b3-11ea-93e4-fb4135ff70cc.png)

**Output from "Gradle Tasks"**
[info] Gradle server started
[info] Gradle client connecting to server...
[info] WebSocketClient: retry in 1000ms
[info] Connected to 127.0.0.1:57312. Welcome client!
[info] CONFIGURE SUCCESSFUL in 9s
[info] CONFIGURE SUCCESSFUL in 128ms

**Comment by badsyntax** [comment]
Hi. This extension is not compatible with the task explorer extension, as stated in the troubleshooting section of the README. Please disable that extension and try again.

**Comment by AceHack** [comment]
That worked, thank you

**Comment by badsyntax** [comment]
Great, thanks for letting me know. This issue seems to be quite common, but I haven't been able to provide compatibility between the extensions. Perhaps if I have more time in the future I can figure out a nice solution.
