### ISSUE TITLE
Going beyond Gradle Tasks - Ease of executing gradle commands

### ISSUE THREAD

**Issue by hannah23280** [microsoft/vscode-gradle#308]
Hi,

As i believe that vscode-gradle's  main feature is to allow developer to easily run gradle tasks, but i 
 was wondering whether if there is any intention to enhance the extension to go beyond that.
One suggestion i could think of is to allow developers to easily trigger commonly used gradle built-in commands such as kill specific (or all) daemons (using gradle --stop) , check gradle (using gradle --status), etc with some UI buttons, perhaps displayed at the top of the gradle tasks pane or display in a new pane (called gradle commands)

The result could be displayed in new terminal.
Benefit: To speed up the execution of these commands, as developer does not have to hunt for the actual command to trigger.

Just a 2 cent worth of suggestion

**Comment by badsyntax** [comment]
Hey, thanks for the suggestions. Yes I have been thinking about this, and do plan on enhancing the extension to provide extra features similar to the ones you mentioned. I'm putting a lot of effort to get the task operations working nicely first. 

Some features I was thinking about:

- Create new [sub-project](https://docs.gradle.org/current/userguide/multi_project_builds.html)
- Create new task
- Gradle status 
- Kill daemons
- Create new gradle project (using `gradle init`)

If there's anything else you'd feel would be useful, let me know and I'll consider it for future updates.

**Comment by hannah23280** [comment]
Great to hear your plan!

The reason why i raised this is because i read issue #225 , and somehow I think i have same kind of query as him , albeit not a big issue.  That is what lead to me think of this enhancement which allow us to trigger the kill daemons by simply clicking a button without having to manually type the gradle command in the terminals to kill it.

Hence meanwhile i have nothing useful to suggest yet, but "kill daemons" would be a nice addition. 
Would reply to this thread if i came up with any feature that would be practically useful.

**Comment by badsyntax** [comment]
Cool. Am trying to better understand the context for this feature. Can you let me know *why* you want to kill the daemons?

**Comment by hannah23280** [comment]
Could not remember long time back why i want to kill the daemons. 
but i manage to find some extraction from gradle books

"Although the gradle daemon is recommended for the development environment, it 
might get corrputed occasionally. When gradle executes user build scripts from multiple sources (for example, in the continuous Integration environment), it might exhaust the daemon process and may cause memory leakage if resources are not handled properly.
Therefore it is recommended not to enable the daemon for staging or continuous integration environment.
...
"The gradle team strongly recommends you do not use the daemon on CI servers, which value stable and repeatable builds more than performance."

From the above quotes, although CI environment typically does not install vscode, but considering that developer might use their development machine (with vscode installed) to test out CI or to do something which value stable and repeatable builds more than performance, they might want to kill the daemon.

Of course, in real practical world, I rarely wanted to kill daemon, hence it is not really a much needed feature for me, but cool to have.

**Comment by hannah23280** [comment]
Actually i was thinking aloud that it is virtually impossible to add UI buttons for each and every possible gradle commands available.  

One alternative could be to allow developer to specify the command they use frequently, by typing into an input box provided by the vscode-gradle or specify inside the settings.json which expects an array.  Then the gradle pane will display the specified commands in a drop-down box for developer to choose and execute.

**Comment by badsyntax** [comment]
I agree that it could be useful for some people to be able to stop the gradle daemons. From some of the linked issues it appears some people have memory related issues. In those scenarios, it's up to the user to understand the consequences of killing the daemons, but it would be useful to provide that option to the user. 

It would also be useful to visualise the running daemons, to see how many have been spawned, which are idle etc. 

> Actually i was thinking aloud that it is virtually impossible to add UI buttons for each and every possible gradle commands available.

Why do you say this? 

As this extension uses the Gradle Tooling API, there are indeed some limitations, but in those cases I can fallback to using the wrapper script or the globally installed gradle execution (for example running `gradle init`).

**Comment by hannah23280** [comment]
> I agree that it could be useful for some people to be able to stop the gradle daemons. From some of the linked issues it appears some people have memory related issues. In those scenarios, it's up to the user to understand the consequences of killing the daemons, but it would be useful to provide that option to the user.

Very agree

> 
> It would also be useful to visualise the running daemons, to see how many have been spawned, which are idle etc.

 I assume u mean something like display the no. of running daemons on a pane for developer to see visually. In that case that would be cool.  
But a simpler alternative (as in simpler for you as the extension maintainer), is to open a new terminal and output the result of the gradle command (gradle --status), which displays the currently running daemons.  The disadvantage of the latter is that it is less visiually appealing, since display on terminals are boring to view. :). But advantage is that terminals can displays a lot of information on terminals than u can squeeze on the pane.
> 
> > Actually i was thinking aloud that it is virtually impossible to add UI buttons for each and every possible gradle commands available.
> 
> Why do you say this?

Ignore what i say for this.
 I realize a lot of gradle commands are actually running gradle tasks (e.g build, run, etc) which are already available in the gradle tasks pane.  Hence the new features u planned to add is for those commands that have nothing to do with running gradle tasks. E.g killing the daemons and displaying the status. Correct me if i am wrong. 

Previously u also mention a suggested feature in earlier post to "Create new gradle project (using gradle init)". I thought currently we can already do that by running the gradle task called init. Hence should be no needed for this new feature.

**Comment by badsyntax** [comment]
Thanks for the feedback, it's super helpful. 

> I assume u mean something like display the no. of running daemons on a pane for developer to see visually. In that case that would be cool.
But a simpler alternative (as in simpler for you as the extension maintainer), is to open a new terminal and output the result of the gradle command (gradle --status), which displays the currently running daemons. The disadvantage of the latter is that it is less visiually appealing, since display on terminals are boring to view. :). But advantage is that terminals can displays a lot of information on terminals than u can squeeze on the pane.

Yep, was thinking of showing the daemon status in a custom view somewhere. But I might consider your suggestion, of allowing users to run commands (eg `./gradlew --status`) as well as tasks. The output will be displayed in a custom terminal, exactly how tasks are run. 

> Previously u also mention a suggested feature in earlier post to "Create new gradle project (using gradle init)". I thought currently we can already do that by running the gradle task called init. Hence should be no needed for this new feature.

Yes this is a good point, it's just another task. I was thinking about making project init easier for the user, and providing some sort of UI wizard with forms, which i'll use to pass arguments to the init task. (Arguments are mentioned here: https://docs.gradle.org/current/userguide/build_init_plugin.html)

**Comment by badsyntax** [comment]
I've been playing around with this, and here's a screenshot of what i'm thinking about: 

<img width="1504" alt="Screenshot 2020-05-23 at 12 52 03" src="https://user-images.githubusercontent.com/102141/82729996-60e82000-9cf4-11ea-8b8a-3939efd317a8.png">



Changes:

- The tasks have been moved into a dedicated view which can be accessed via the activity bar. (The vertical bar on the left). 
- It now shows the Gradle daemons, with PID & status, and the user will be able to kill specific or all daemons.

I've put the tasks into a dedicated view because I found it difficult to navigate the tasks tree when displayed in the explorer, especially when working with multi-projects. Also moving the tasks to a dedicated custom view allows me to add other Gradle specific features (like the daemons listing) 

Now that we have a dedicated view, we can add other Gradle features. But i'm still trying to decide what will be useful there.

**Comment by hannah23280** [comment]
Waoo! The gradle daemons view, with the ability to kill specific or all daemons is definitely cool...I will surely be waiting for that...
Below is my 2 cent worth of suggestions which I hope can give some ideas on how to leverage the dedicated view.

Suggestion 1:  "list bookmarked tasks".  
-----------------------------
Developers can bookmark their frequently-used tasks, and their "bookmarks" will appear in the "list bookmarked tasks" , hence speeding up task trigger.
For me, i have a root project, with multiple nested gradle projects. Currently,  if i wanted to execute "bootRun"  task for each of the nested gradle projects. Under "GRADLE TASKS" , I have to expand for EACH of the nested gradle projects, in order to find the "bootRun" task to trigger it.    
How nice, if we can have the ability to add "bookmark" for the "bootRun" task under each nested gradle projects, then i can avoid having to expand and contract repeatedly in order to view the tasks for each nested projects.

Suggestion 2:  "list running tasks".  
----------------------------------
Display a list of gradle tasks (which has associated terminals being opened).  E.g 
1. check
2. clean
3. compileJava
Each of the listed task can be a link, such that if we click on the task link, it will open the corresponding terminal that is currently running that task.  This is better than user having to click on the Terminal drop down list, and then choose the terminal associated with the task. Cos the former is a one-click action, the latter is a two-click action. 
Imagine switching between different terminals to see the status of the different tasks.

**Comment by badsyntax** [comment]
Thanks for the feedback! I like suggestion 1. I also often run the same tasks, but in this case i usually do it through the "Run Task" vscode command, which remembers the tasks I run often. But saying that, I would also find it useful to bookmark tasks, as there are cases where I need to run non-common/deeply-nested tasks, and I agree it's annoying to have to navigate the big list of tasks to find these tasks. I think it's a great suggestion and I'm keen to implement it.

Here's a rough mockup of how it could work:

<img width="1440" alt="Screenshot 2020-05-23 at 17 42 12" src="https://user-images.githubusercontent.com/102141/82735861-d536b980-9d1c-11ea-8ccb-38c1825d5b9b.png">

Does this match your understanding? I'm thinking to render it as a single (non-nested) list for easy access. It does mean i'll need to prefix the project names to the tasks. And in the case of vscode multi-root projects, i'll also need to prefix the vscode project. I'll give it some more thought, but I think this could work. 

For suggestion 2, i'd like to understand your use case and workflow a bit better. For the tasks you listed, does it make sense to run those at the same time? Is it realistic those tasks will all be running? Are you also thinking along the lines of "tasks that have run but also finished"?

**Comment by hannah23280** [comment]
Hi, 
Yes! The mockup u made is exactly what i am visualizing too.

For suggestion 2, 
Use case 1
----
I am creating microservices (which is the popular architectural styles nowadays). Each gradle sub-project is a microservice.  Since microservices would typically need to interact with one another to serve a request, hence would need to run them together. Sometime, the sub-project could be an eureka server, which microservice would need to interact with as well.   
This suggestion will display list of task names, allowing developer to have a bird-eye view of what tasks are currently running 
e.g

1. microservice1:bootRun  [stop button]
2. microservice2:bootRun [stop button]
3. eurekaservice:bootRun [stop button]

Let's say, if i decide to stop all these services, I can simply click the stop button beside each running task to stop them. Rather than having to manually  expand/collapse each subproject in order to view the task that I want to stop.   It would even be a great bonus, if there is a stop button to stop all running tasks in one click

Another reason for running multiple gradle projects at same time is when I wanted to run server-side application and a client-side application at same time. Both are separate gradle projects. Server need to be running, then client run and connect to it. 

Use case 2
-----------
Everytime I run a gradle task, a terminal open for it. Once task completed, the terminal will remain open.  It is okay for the terminal to remain open after task completed. But as development progress, I will unknowingly be running many tasks, say 20 tasks, and 20 terminals will be opened.  When I decides to close these terminals , I have to **repeatedly** go to the terminal's dropdown box to choose each terminal, before closing it (a 2-step action).  20 terminals will result in 40 steps action. And that is tedious.  So this suggestion will provide a quickie way to close multiple gradle-related terminals.

**Comment by badsyntax** [comment]
Thanks for this. It makes sense. I'll add this feature. 

There's a lot of features here, so i'm managing the project with: https://github.com/badsyntax/vscode-gradle/projects/1

The only big difficulty I can see is adding the Gradle Daemons feature, as I can't get this information through the Gradle Tooling API, and will need to use the Gradle Wrapper instead. I don't see this as a blocker, but just more work, so this feature is low on the list. I'll tackle the other features first.

**Comment by badsyntax** [comment]
In the end I decided to work on the gradle daemons feature first 😂 You can see updated screenshots in this draft PR: https://github.com/badsyntax/vscode-gradle/pull/434

**Comment by hannah23280** [comment]
Can i ask: "if u click the square button", the daemon is stopped, but it will continue to be listed. Only if u click the "x" beside it, then it will be removed from the list. Is my understanding correct?

And also, clicking the "square button" to stop the daemon is equivalent to gradle --stop ?

**Comment by badsyntax** [comment]
> Can i ask: "if u click the square button", the daemon is stopped, but it will continue to be listed.

Yes stopped daemons will continue to be listed. The underlying processes are dead/don't exist, but Gradle still remembers the stopped daemons for an hour, and there's no easy way to tell Gradle to "stop remembering these stopped daemons".

> Only if u click the "x" beside it, then it will be removed from the list. Is my understanding correct?

No. Perhaps the "x" icon is misleading. There's nothing you can do to hide the stopped daemons. There's no corresponding commands you can execute on them. They will continue to be displayed there for an hour. The list can get pretty big as Gradle recycles it's daemons, but they will eventually go away. Perhaps I can improve the UI a bit, and show them in a "disabled" state with a faded text color, or something like that, to make them less distracting.

> And also, clicking the "square button" to stop the daemon is equivalent to gradle --stop ?

The red square button in the treeview header is equivalent to `gradlew --stop` and it will stop all demons.
The white square button next to the daemon rows will just stop the specific daemon, and is equivalent to `kill -9 PID`

**Comment by badsyntax** [comment]
PR https://github.com/badsyntax/vscode-gradle/pull/434 is coming along nicely. I should be able to release a BETA version of the extension in the next few days to allow you to test this feature yourself.

**Comment by badsyntax** [comment]
Hey @hanct I've published a BETA version. You can install it here: https://marketplace.visualstudio.com/items?itemName=richardwillis.vscode-gradle-preview

(You'll need to disable the stable "Gradle Tasks" extension first.)

This version only contains these features:

 - Dedicated Gradle view in activity bar
- List/kill Gradle daemons

I'll work on the "Boookmark Tasks" feature next. 

Any feedback is most welcome! Thanks!

**Comment by hannah23280** [comment]
Ok!  Here's the feedback


As seen from screenshot below, I have disabled the stable version, and install the preview version.
But yet no gradle-related view appears...
![image](https://user-images.githubusercontent.com/4410920/82832817-cef83700-9eee-11ea-9372-27ca0a614b69.png)

![image](https://user-images.githubusercontent.com/4410920/82832871-f818c780-9eee-11ea-9122-c7358c546a2e.png)


Then i revert back my stable version, and disable the preview version, and restart IDE, and my gradle tasks view appears again.

**Comment by badsyntax** [comment]
The view has been moved to a dedicated view container. You won't find it in the explorer. There should be a Grade icon in the left sidebar (called activity bar) that will open the Gradle view. Can you post a full-size screenshot?

**Comment by hannah23280** [comment]
Yeah. I saw it!  
Feedback: When i try running a task, i keep getting prompt "There are task errors, See the output for details", as shown in the screenshot below
![image](https://user-images.githubusercontent.com/4410920/82834538-05848080-9ef4-11ea-81b6-77632f2bdb62.png)

So i click to see more details as shown below. **Do note that reverting back to the stable version, I no longer see the error prompt when running a gradle task.**

![image](https://user-images.githubusercontent.com/4410920/82835056-7c6e4900-9ef5-11ea-8819-452b8e490e52.png)

Although i keep getting prompt on the task errors, but i did see via the task terminal that it is running successfully
![image](https://user-images.githubusercontent.com/4410920/82835006-55177c00-9ef5-11ea-8cfa-ded5a6d68741.png)

**Comment by badsyntax** [comment]
Thanks for the testing.

When you get that error and click on "Show output", can you take a screenshot that includes the output panel type (the dropdown). I don't know what's reporting that error, if it's vscode, or an extension. Thanks!

**Comment by badsyntax** [comment]
I also see you're using a "Tasks" extension, does the error still occur if you disable that extension?

**Comment by badsyntax** [comment]
Although I don't understand why it's occurring (I can't replicate), I think I know how to fix it. Will let you know when I've released a new BETA version.

**Comment by badsyntax** [comment]
Can you also let me know if you've referenced any gradle tasks in your `tasks.json`?

**Comment by hannah23280** [comment]
> Thanks for the testing.
> 
> When you get that error and click on "Show output", can you take a screenshot that includes the output panel type (the dropdown). I don't know what's reporting that error, if it's vscode, or an extension. Thanks!

![image](https://user-images.githubusercontent.com/4410920/82855237-4bb20200-9f3d-11ea-9985-b9b6304a7ba1.png)

**Comment by hannah23280** [comment]
> I also see you're using a "Tasks" extension, does the error still occur if you disable that extension?

Hi, if u look at the screenshot, u notice that "Tasks" extension isn't installed, as it has the label "Install" beside it

**Comment by hannah23280** [comment]
> Can you also let me know if you've referenced any gradle tasks in your `tasks.json`?

Yes. There is. Frankly speaking, i not even remember creating this task in the task.json. But I observe that once i removed it, the error output no longer prompted!  Now i put it back again, so that i can test it in case u have make a fix for it.  

![image](https://user-images.githubusercontent.com/4410920/82855587-46a18280-9f3e-11ea-847e-f657d94bcc9d.png)

**Comment by badsyntax** [comment]
Thanks for the screenshots.

> Hi, if u look at the screenshot, u notice that "Tasks" extension isn't installed, as it has the label "Install" beside it

Sorry my bad 🤦 

I see now that it's a vscode error. With these screenshots I will be able to replicate the issue. I'm not sure how that task ended up in `tasks.json`, but I will be able to provide support for doing that. 

I've also noticed some performance degradations, so i'll spend a bit of time fixing that before pushing out a new release.

**Comment by badsyntax** [comment]
I've added some fixes and released a new BETA version (`0.0.115437617`) if you want to test it again. Thanks.

**Comment by badsyntax** [comment]
I've now published a new BETA that incudes the "bookmark tasks" feature. You can see an updated screenshot in this PR: https://github.com/badsyntax/vscode-gradle/pull/441

Please update to the latest BETA version to test.

Some thoughts on the latest changes:

- I don't find the Gradle daemons very useful, but happy to keep it as others might find it useful
- Loading the Gradle daemons is slow as it executes the Gradle wrapper. There's not much I can do to speed it up. The loading indicator sometimes goes crazy when running a task that completes quickly. I can try find a way to cancel the daemon refreshing to prevent queued refreshes.
  - Note that if you collapse the daemons view, it won't refresh, so this is a good "workaround" for those who don't like this feature (like me)
- Loving the bookmarked tasks feature!
- I should display a message in the Bookmarked Tasks view if no tasks have been bookmarked.

As always, any feedback is welcome. Thanks!

**Comment by hannah23280** [comment]
Thanks! I have tested.  So far, no issue encoutered!

> I don't find the Gradle daemons very useful, but happy to keep it as others might find it useful

For me, i would use it to stop all the daemons, rather than specific one.  So if you observe that the use case to stop one specific daemon is very rare, then one alternative is to remove this listing of daemons but can retain the button to stop all running daemons.  

>Loading the Gradle daemons is slow as it executes the Gradle wrapper. 

Just curious, what happen if the user did not use Gradle wrapper?

>Note that if you collapse the daemons view, it won't refresh, so this is a good "workaround" for those who don't like this feature (like me)

Or u can hide the daemons view. :) . And i assume hiding it won't refresh too.

>Loving the bookmarked tasks feature!

Me loved the bookmarked task too! Now i can save several trips down to search for my most recently used task.Thanks for the implementation

**Comment by badsyntax** [comment]
Thanks for the feedback. Great to hear there's no issues.

> Just curious, what happen if the user did not use Gradle wrapper?

The Gradle wrapper is a requirement of this extension. You need to have a Gradle wrapper in the root of the project. And I need to use this Gradle wrapper to list the daemons, to prevent users from killing daemons for the wrong Gradle version. 

> Or u can hide the daemons view. :) . And i assume hiding it won't refresh too.

Yes true! So you can either just collapse the view, or hide it completely. In both cases, the daemons won't be refreshed. I still want to make some improvements though, to cancel refreshing the daemons list (as the requests can be queued resulting in a loading indicator that doesn't go away)

> Me loved the bookmarked task too! Now i can save several trips down to search for my most recently used task.Thanks for the implementation

Awesome. Yes it's a very useful feature. Thank you for suggesting it! I will add a credit note in the README thanking you for this suggestion.

**Comment by badsyntax** [comment]
I'm now thinking about how to implement the "Running Tasks" feature.

I'll show a new view with the following list & features (the square brackets are icons):

- `[RUNNING]` Running Task Name `[STOP]` `[TERMINAL]` `[CLOSE]`
- Stopped Task Name `[TERMINAL]` `[CLOSE]`

The `[RUNNING]` icon will be a spinner, the same spinner shown in the other views.
The `[STOP]` icon will stop the running task.
The `[TERMINAL]` icon will show the corresponding terminal. 
The `[CLOSE]` icon will close the corresponding terminal and remove the task from the list (and also stop the task).

Ii'm not sure "Running Tasks" title makes sense, as the view will list both running tasks *and* tasks that have already been run. Maybe "Executed Tasks"? I'll give it a think. 

I also agree that it's annoying that a new terminal is created every time you run the same task. It should be only 1 terminal per task IMO. I've had some difficulty forcing the task to use the same terminal but i'll try fix this.

Sound good? I'll post a screenshot when I have the basic view implemented.

**Comment by badsyntax** [comment]
And btw, do you still think it's worth to create a feature to run arbitrary Gradle commands? Apart from `--status` and `--stop` (which are now implemented in the UI), all the other "commands" can be provided as task args.

**Comment by hannah23280** [comment]
> I'm now thinking about how to implement the "Running Tasks" feature.
> 
> I'll show a new view with the following list & features (the square brackets are icons):
> 
> * `[RUNNING]` Running Task Name `[STOP]` `[TERMINAL]` `[CLOSE]`
> * Stopped Task Name `[TERMINAL]` `[CLOSE]`
> 
> The `[RUNNING]` icon will be a spinner, the same spinner shown in the other views.
> The `[STOP]` icon will stop the running task.
> The `[TERMINAL]` icon will show the corresponding terminal.
> The `[CLOSE]` icon will close the corresponding terminal and remove the task from the list (and also stop the task).

That's cool! Love the suggested 4 options.  

> Ii'm not sure "Running Tasks" title makes sense, as the view will list both running tasks _and_ tasks that have already been run. Maybe "Executed Tasks"? I'll give it a think.

"Executed Tasks" sound ok to me, except that some people might thought that this is a history of ALL previously executed tasks, when actually this only listed previous executed task with open terminals. Hence other choices could be "Tasks with open terminal" and  "Opened Task Terminals"

**Side Note:**
An idea pop up in my mind that you could consider implementing a feature called "Recent Tasks" instead. It listed all previous triggered tasks with or without an associated terminals. And if user close the terminal for that task, be it via the terminal close feature or [CLOSE], the task can remain  in the "Recent Tasks" view, just that it do not have the [TERMINAL] icon anymore.

This would be useful for those people who loves to review what are the previous task they executed, 
and even allow them to run again, in fact, with the same arguments! 
E.g I run the build task with the args "--info".  The "recent tasks" will list the build task, and even keep track of the args used.  So the next time, i want to rerun the build task multiple times with the same args, I just run the task in the "Recent Tasks" and no need to enter the args again and again. Time savior! A feature that can close selected task terminals very quickly, and allow execution of previously run task without having to manually enter args again and again.

Just a 2 cent worth of suggestion. :)

> 
> I also agree that it's annoying that a new terminal is created every time you run the same task. It should be only 1 terminal per task IMO. I've had some difficulty forcing the task to use the same terminal but i'll try fix this.

May I ask if u  decide to force the task to use the same terminal, would u be clearing away the existing display message for the previously runned task, or simply append the message for the newly running task to the previous one?  

Actually once u provide the fast way of closing terminal via [CLOSE], user can quickly closed all those "annoying" terminals very conveniently. hence this feature of  having 1 terminal per task would become very low priority, IMO.

**Comment by hannah23280** [comment]
> And btw, do you still think it's worth to create a feature to run arbitrary Gradle commands? Apart from `--status` and `--stop` (which are now implemented in the UI), all the other "commands" can be provided as task args.

I agree with you. Think this feature might not be worth implementing anymore, given what is already implemented

**Comment by badsyntax** [comment]
Great suggestions again! Thank you.

I like the "Recent Tasks" approach.

About the close functionality, I agree that it will just close the terminal/s but keep the task in the list. If the user wants to remove the recent task from the list, I'll add a context menu option called something like "Remove Recent Task". I'll also provide an icon/button in the list header to clear the recent tasks list. 

> May I ask if u decide to force the task to use the same terminal, would u be clearing away the existing display message for the previously runned task, or simply append the message for the newly running task to the previous one?

I was going to try keep the terminal history. But I'm not absolutely convinced to change this. If you find it's useful to have separate terminals every time the same task is run, then I won't change. I imagine some people might find this useful, to refer to existing task executions. 

> Actually once u provide the fast way of closing terminal via [CLOSE], user can quickly closed all those "annoying" terminals very conveniently. hence this feature of having 1 terminal per task would become very low priority, IMO.

Yes I agree. So for now I won't change this behaviour.

**Comment by badsyntax** [comment]
For recent tasks, this will be limited to the vscode session, and will disappear when you close vscode. Does this match your understanding? Would you prefer for vscode to remember the recent tasks, even after you've closed vscode? I'm not sure if that makes sense, as "recent tasks" suggest they are tasks run within the session, and not at some point in the past.

**Comment by hannah23280** [comment]
> For recent tasks, this will be limited to the vscode session, and will disappear when you close vscode. Does this match your understanding? Would you prefer for vscode to remember the recent tasks, even after you've closed vscode? I'm not sure if that makes sense, as "recent tasks" suggest they are tasks run within the session, and not at some point in the past.

For me, I would prefer to retain the recent tasks when vscode is closed.  
For others who prefer to have recent tasks displayed empty whenever vscode is reopened, they can just clear all tasks with a button click.   
Hence if  retain, both preferences can be satisfied

A real life use case: 
At my working place, we developers have our own development pc. Normally, when we leave our office, we usually leave our PCs on, so that our IDEs will always remain open. 
The problem is that many times these PCs tend to restart by itself at night cos of some windows updates pushed down by our corporation. So many time when we come to work, we have to start up our machine and then our ide.  So if the recent tasks are all cleared upon ide startup, that mean we would lose all the recent commands (and arguments) we executed yesterday  , and hence have to retype them again. 

But luckily this is not a show stopper , so I thought the decision would perhaps depend on whether if it is easy to implement retaining the recent tasks whenever vscode is closed. 
If difficult to do, then can make thing simple by not retaining them.

But if u decide to go ahead to retain the recent tasks , developers might actually retain these tasks for a long time. In that case, look like we cannot call this feature "recent tasks" anymore.  Maybe can use your earlier suggested name - "**Executed Tasks**".

**Comment by badsyntax** [comment]
It's not hard to implement. It's more about, does it make sense to remember recent tasks when we already have bookmarked tasks? The bookmarking tasks with args feature is missing (and I could add this) but otherwise remembering recent tasks would be a similar feature to bookmarked tasks and the definition of the two views becomes unclear.
 
It's hard to visualise/imagine the UX and make decisions without having a working version, so I'll get this implemented so we can try it, then we can discuss the details on how it should work 👍

**Comment by hannah23280** [comment]
> It's not hard to implement. It's more about, does it make sense to remember recent tasks when we already have bookmarked tasks? The bookmarking tasks with args feature is missing (and I could add this) but otherwise remembering recent tasks would be a similar feature to bookmarked tasks and the definition of the two views becomes unclear.
> 
> It's hard to visualise/imagine the UX and make decisions without having a working version, so I'll get this implemented so we can try it, then we can discuss the details on how it should work 👍

Agree that we can see the working version first, otherwise difficult to visualize.
Btw, actually you give me an idea when u mention about bookmark.  

We can also allow user to bookmark task (together with its arg) in the "recent tasks" view, assuming u r okay to support args in bookmarks.
In that case, it should be okay to clear away the recent tasks when vscode is closed.  
But that would mean that the bookmark view should allow display of same task names multiple times, since user might want to bookmark same task several times, each with a different set of args.

This would hopefully distinguish between "Recent Tasks" with 'Bookmark Tasks".

**Comment by badsyntax** [comment]
I have decided to not include the "Create new Gradle Project" feature into the next big release. I'm not convinced it's a useful feature. 
All the others changes will be released with https://github.com/badsyntax/vscode-gradle/pull/433 and it's very close now.

**Comment by badsyntax** [comment]
Released with https://github.com/badsyntax/vscode-gradle/releases/tag/3.1.0

@hanct thanks for your suggestions and testing, it's really appreciated. I've added a credit for you in the README: https://github.com/badsyntax/vscode-gradle/blob/master/README.md

If you like this extension smash that "Star" button :)
