### ISSUE TITLE
error when connecting to gradle server (tasks-server.bat)

### ISSUE THREAD

**Issue by EdoFro** [microsoft/vscode-gradle#333]
Extension Name: vscode-gradle
Extension Version: 2.7.7
OS Version: Win 10
VSCode version:
> Version: 1.44.2 (user setup)
> Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
> Date: 2020-04-16T16:36:23.138Z
> Electron: 7.1.11
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Windows_NT x64 10.0.18363

**Describe the bug**
It can't connect to gradle server.
When using the debug setting it says it has problem with part of the path of the JAVA.

the Path to java in my computer is:
**C:\Program Files (x86)\Java\jdk-14.0.1**

and the **tasks-server.bat** fails because of the parentesis **)** in this path

it thinks that the parentesis is a part of the if - else statement when executing. It throws an error message like "**not expecting: \Java\jdk-14.0.1**" 

**To Reproduce**
1.  java path with a "**)**" in it

**Expected behavior**
gradle server connects

**This is what I did to bypass the error for this time:**
 in the tasks-server.bat file stands:
```batch
:findJavaFromJavaHome
if defined VSCODE_JAVA_HOME (
  set _JAVA_HOME=%VSCODE_JAVA_HOME:"=%
) else (
  set _JAVA_HOME=%JAVA_HOME:"=%
)
set JAVA_EXE=%_JAVA_HOME%/bin/java.exe
```

I modified it to this and it got solved:
```batch
:findJavaFromJavaHome
::if defined VSCODE_JAVA_HOME (
::  set _JAVA_HOME=%VSCODE_JAVA_HOME:"=%
::) else (
  set _JAVA_HOME=%JAVA_HOME:"=%
::)
::set JAVA_EXE=%_JAVA_HOME%/bin/java.exe
set JAVA_EXE=%_JAVA_HOME%\bin\java.exe
```

**Comment by badsyntax** [comment]
Thanks for this report! I was able to replicate this bug and have submitted a fix with https://github.com/badsyntax/vscode-gradle/pull/334

I'll release the fix sometime today.
