### ISSUE TITLE
How to pass args for Debug?

### ISSUE THREAD

**Issue by hannah23280** [microsoft/vscode-gradle#354]
vscode: v2.7.7
vscode: v1.44.2
Hi,

vscode-gradle provides 2 menu items:  Run Task and Run Task with Args.  
For debug, how do I pass in args  ?
My use case is to add --info

**Comment by badsyntax** [comment]
Thanks for the suggestion. I'm not sure how/why i missed this. I will add this feature. 
It'll work the same as run, so I'll add a new option to the context menu called "Debug task With Args".
I'll try add this in the next couple of days.

**Comment by badsyntax** [comment]
I'll release the fix sometime today.

**Comment by badsyntax** [comment]
This fix has been released. Can you update the latest version to test and re-open this ticket if there are any issues?

I've also added some other features including better task cancelling (now the terminal is not closed when cancelling) and I've fixed the gradle progress when running tasks. Let me know if you like the new changes or not.

**Comment by hannah23280** [comment]
Hi,
Thanks for the fix. I update to v2.7.10 and restart my IDE. Then i right click on the task which i enable the debug, but the menu only has "Debug", butl no "Debug task With Args"

**Comment by badsyntax** [comment]
Can you update to the latest? V3.0.1

**Comment by hannah23280** [comment]
Hi, my visual studio code could not see any further update for vscode-gradle extension. That is, it stop at v2.7.10

**Comment by badsyntax** [comment]
Hmm, I think you need to update vscode to latest. Are you on an older version of vscode?

**Comment by badsyntax** [comment]
I will make a change to support older versions of vscode. This is my mistake.

**Comment by hannah23280** [comment]
Hi, I have updated to the latest vscode and manage to get the latest download of vscode-gradle!  So far it works okay. I can see the debug with args, and can use it successfully!

As for better task cancelling (now the terminal is not closed when cancelling) 
Qn: how do I suppose to cancel the task? Ctrl-Alt-delete in the terminal? 

and I've fixed the gradle progress when running tasks.
Qn: how can i help to verify this?

**Comment by badsyntax** [comment]
thanks for testing. i will make a change to support older versions of vscode regardless.

>  how do I suppose to cancel the task? Ctrl-Alt-delete in the terminal?

You cancel the task using the stop button in the explorer, or, when focusing on the terminal, cancel the task as you would cancel a normal shell process, using [SIGINT](https://en.wikipedia.org/wiki/Signal_(IPC)#SIGINT). Basically CTRL+c.  Or you can cancel via the status bar, or you can just close the terminal.

The change I made was to keep the terminal open when cancelling a task so you can see the task output. Previously, when you cancelled a task (eg with the stop button), the terminal would just close, and you couldn't see the task output.

> how can i help to verify this?

now when running tasks you'll see the gradle progress bars in the terminal. previously you would only see fragments of this progress bar, or the terminal would be blank until the task output something. now, as soon as you run a task you should now see progress in the terminal. it should also show progress of the various daemons. it's kinda hard to test, as it depends on gradle cache. you can try run "gradle clean" and then something like "gradle assemble" to see the progress.

**Comment by hannah23280** [comment]
Noted!
The cancelling of the task - verified working! The terminal did remain open, even when click the stop button

As for the gradle progress bars, after i run gradle clean, I proceed to run gradle assemble, i can immediately see the progress as in "<-------------> 0% EXECUTING [2s]".  Hope this is what I should be expecting.

**Comment by badsyntax** [comment]
Thanks for testing! I really appreciate it. Yes that's all correct.
