### ISSUE TITLE
Extension conflict: The "path" argument must be of type string error

### ISSUE THREAD

**Issue by zengfr** [microsoft/vscode-gradle#37]
refersh note:  The "path" argument must be of type string. Received type undefined
Screen capture at right bottom:
![1](https://user-images.githubusercontent.com/9524903/68522907-6fd52b00-02ec-11ea-8572-389ed3f7d27c.PNG)

**Comment by badsyntax** [comment]
hi. you have a bunch of extensions enabled and it's hard to know what's causing the error.

can you try the following:

1. Update to the latest version of "Gradle Tasks" extension (search for the extension in the extensions panel, then click update)
2. Disable all other extensions
3. Open the "Output" panel and select "Gradle Tasks". Paste the output here.

thanks

**Comment by zengfr** [comment]
is resolved .
Task Explorer/vscode-gradle  2 plugins  is conflicted

**Comment by badsyntax** [comment]
Thanks for the feedback. I'm going to re-open to do some investigations on this other extension, to prevent conflicts. I'd like to understand why it's conflicting.

**Comment by badsyntax** [comment]
I wonder if there's a way to achieve interoperability between the extensions. I see the Tasks Explorer extension has the ability to list tasks not provided by itself. I will investigate if vscode-gradle can provide the task for the Tasks Explorer extension. 
I also question the usefulness of the Tasks Explorer providing the gradle tasks itself because as far as I can tell it doesn't actually run gradle to provide the tasks, it just parses build.gradle, but I need to do more investigation.

**Comment by badsyntax** [comment]
These are the outcomes of my brief investigation:

* The tasks explorer extension provides gradle tasks by parsing the gradle build files. It is not very useful as it does not support `tasks.register`, kotlin build files, sub-projects, nor list the default well-known tasks. 
* Although the error mentioned in this ticket is preventing the "Gradle Tasks" extension from showing tasks, we already see the possibility of some interoperability with the Tasks Explorer extension:

<img width="427" alt="Screenshot 2019-11-13 at 10 55 04" src="https://user-images.githubusercontent.com/102141/68753095-b2f11000-0604-11ea-82dd-4b17b5240a9a.png">

This is my proposal:

* As the "Gradle Tasks" extension actually uses gradle to list tasks, it is much more useful than the approach taken by "Tasks Explorer"
* If both extensions are installed, then the "Task Explorer" extension should use "Gradle Tasks" to provide the tasks, and not attempt to provide gradle tasks itself
* If both extensions are installed, then "Gradle Tasks" should continue to work as expected

**Comment by zengfr** [comment]
Very good, great.

**Comment by badsyntax** [comment]
For the meantime you'll have to disable the task explorer extension if you want to use this extension.

**Comment by badsyntax** [comment]
I've released a fix for this with version 2.1.7. You can see screenshots in https://github.com/badsyntax/vscode-gradle/pull/48 Let me know if it's still an issue.
