### ISSUE TITLE
Create "Recent Tasks" feature and treeView

### ISSUE THREAD

**Issue by badsyntax** [microsoft/vscode-gradle#450]
Refs https://github.com/badsyntax/vscode-gradle/issues/308

Requirements

### UI:

- [RUNNING] Running Task Name [STOP] [TERMINAL] [CLOSE]
- Stopped Task Name [TERMINAL] [CLOSE]

### Features overview:

- The [RUNNING] icon will be a spinner, the same spinner shown in the other views.
- The [STOP] icon will stop the running task.
- The [TERMINAL] icon will show the corresponding terminal.
- The [CLOSE] icon will close the corresponding terminal and stop the task and remove the [TERMINAL] icon
- The Running Task will have to show the args (either with tooltip or as part of the name).

### View header options:

- Close all tasks (close their terminals)
- Clear list (remove them from the list)

### Concerns:

The [TERMINAL] feature might be hard to implement as the task might have multiple corresponding terminals. I'll see if it makes sense to build a dropdown but i'm not sure the vscode API allows that.

**Comment by badsyntax** [comment]
@hanct let's bring the conversation about recent tasks into this issue so it's easier to follow:

Here's a mockup:

<img width="1352" alt="Screenshot 2020-05-29 at 12 33 55" src="https://user-images.githubusercontent.com/102141/83255770-fb3edc80-a1a8-11ea-84f0-144b8007e8bd.png">

Some things to note:

The recent tasks will behave exactly like other tasks (so you can run the task, cancel the task, restart the task etc) as well as provide other features like show the most recent terminal and close all terminals.

If I add a "bookmark task with args" feature, and don't remember the recent tasks when you close vscode, then I think this will be good enough. What do you think?

**Comment by hannah23280** [comment]
> @hanct let's bring the conversation about recent tasks into this issue so it's easier to follow:
> 
> Here's a mockup:
> 
> <img alt="Screenshot 2020-05-29 at 12 33 55" width="1352" src="https://user-images.githubusercontent.com/102141/83255770-fb3edc80-a1a8-11ea-84f0-144b8007e8bd.png">
> 
> Some things to note:
> 
> The recent tasks will behave exactly like other tasks (so you can run the task, cancel the task, restart the task etc) as well as provide other features like show the most recent terminal and close all terminals.
> 
> If I add a "bookmark task with args" feature, and don't remember the recent tasks when you close vscode, then I think this will be good enough. What do you think?

I think its good enough. But where would u intend to add the "bookmark task with args" feature. 
At the GRADLE Tasks or Recent Tasks ?

**Comment by hannah23280** [comment]
> @hanct let's bring the conversation about recent tasks into this issue so it's easier to follow:
> 
> Here's a mockup:
> 
> <img alt="Screenshot 2020-05-29 at 12 33 55" width="1352" src="https://user-images.githubusercontent.com/102141/83255770-fb3edc80-a1a8-11ea-84f0-144b8007e8bd.png">

Under the RECENT Tasks, i assume the number beside each task represent the number of times that task has been executed, and the play button is to playback that specific task. If what i assume is correct, what happen if same task is executed twice, but with different set of arguments, will it still display as, for example, build (2) ?  If yes,  if i execute it, which set of arguments will it execute with?

**Comment by badsyntax** [comment]
> I think its good enough. But where would u intend to add the "bookmark task with args" feature.
At the GRADLE Tasks or Recent Tasks 

I was thinking of the Gradle tasks, but still to be decided. The easiest way to do it as add another context menu option "Bookmark task with args"

The plan is to treat tasks with args as seperate entities in both the bookmarked tasks and the recent tasks but not sure yet how to display them.

**Comment by hannah23280** [comment]
> > I think its good enough. But where would u intend to add the "bookmark task with args" feature.
> > At the GRADLE Tasks or Recent Tasks
> 
> I was thinking of the Gradle tasks, but still to be decided. The easiest way to do it as add another context menu option "Bookmark task with args"

Can also. But  u can also consider adding the option to Recent Task as well.  Cos let's say if the user executes a task with a set of arguments and then later find these arguments quite useful, there are 2 ways they can bookmark:

1) In the Recent Task, bookmark this task and arguments   
2) In the Gradle Tasks, bookmark this task via "bookmark task with args", and then have to enter the set of arguments again. 

From the above, seem like bookmark in Recent Task is more quicker and convenient IMO.

> The plan is to treat tasks with args as seperate entities in both the bookmarked tasks and the recent tasks but not sure yet how to display them.

haha...true true. Display is a headache.  If display arguments, the view can really become cluttered. 

So I could only think of displaying an indicator to indicate that a task has arguments. E.g an astrix beside  tasks that have arguments.
But how do user see the arguments?    2 ways
     a) display tooltip to show the arguments when the mouse is above the task (with astrix).
     b) add an "argument" icon beside each task name which when clicked will display a textbox showing the arguments (user can use this textbox to change the arguments, if needed).

**Comment by badsyntax** [comment]
> Can also. But u can also consider adding the option to Recent Task as well. Cos let's say if the user executes a task with a set of arguments and then later find these arguments quite useful, there are 2 ways they can bookmark:

I'll do both 👍 

> haha...true true. Display is a headache. If display arguments, the view can really become cluttered.

There's pros and cons to the different approaches. I'm not sure there's a perfect solution here. So once I have new BETA out we can try different options.

I'd like to try listing the args next to the task name as a first iteration:

<img width="1243" alt="Screenshot 2020-05-29 at 20 09 51" src="https://user-images.githubusercontent.com/102141/83296266-6360e300-a1e8-11ea-996d-063030dce3c9.png">

I'll also add the task args to the tooltip.

Of-course this is less than ideal if the task name is long, as you won't initially see the args, but if you see "duplicated tasks", you should know to either hover over the task name to get the tooltip, or expand the view to see the args.

It would also be useful if i could adjust the "spanner" icon (on the left of the task name) to indicate that the task has args. But I have no idea what adjustments to make haha. Will think about it.

Listing tasks with args involved a bit more work than i was expecting, and I have to refactor a bunch of things, but i'm hoping to get a BETA out in the next few days.

**Comment by badsyntax** [comment]
You can see updated screenshots here: https://github.com/badsyntax/vscode-gradle/pull/452 

Getting close to releasing a BETA.

**Comment by hannah23280** [comment]
I assume the tasks shown in the screenshot do not have arguments, since the arguments aren't displayed. Cos i think u plan to put the args next to the task name as a first iteration:

**Comment by badsyntax** [comment]
Which screenshot are you referring to? Args are definitely displayed in the screenshots in that PR.

**Comment by hannah23280** [comment]
oops. ......think i see wrongly.  Cos when i glance at the screenshot, my mind keep visualizing the arguments would be in different color  than the task name (not sure y i have that thought),  hence my mind took a hasty judgement that there is no arguments. 
 But now i saw it....sorrie for the wrong feedback.

**Comment by badsyntax** [comment]
No worries

**Comment by badsyntax** [comment]
I've released a new BETA with the recent tasks feature. Can you update to the latest BETA version and give it a try? Thanks!

**Comment by hannah23280** [comment]
Tested! So far works great! This really gonna be the best and full-featured gradle plugin. Thanks for all these implementations (and gosh, u really implement fast in just a short period).
 
 2 minor feedbacks
1) Trim the trailing space for the arguments 
As shown in screenshot below, notice that there are 2 bookmarked tasks with same name and set of argument?  Actually i place a space behind --info for one of the bookmark. Although not critical, u can consider trimming the space, so that they won't appear 2 times.   

![image](https://user-images.githubusercontent.com/4410920/83373504-1bfe7080-a3fb-11ea-8d02-350c1b9cca45.png)

2) Clear all recent and clear all bookmarks task should prompt for confirmation
As i am trying out to "close all terminals" in the Recent Tasks, I accidentally click the "clear recent tasks. "  This make me realize whether we should prompt user for confirmation.
I also foresee that   user could spend time setting up their favourite bookmarked tasks, and would dismay if they accidentally clear all their bookmarks tasks, just cos they click the wrong button without being prompt.

**Comment by badsyntax** [comment]
Great thanks for the testing! Not gonna lie it was a lot of work and I had to refactor a lot of code. 

> Trim the trailing space for the arguments

Yes good spot, will do this, it's a quick change 👍 

> Clear all recent and clear all bookmarks task should prompt for confirmation

Cool yes makes sense, I'll do this also. 

Some other things I've been thinking about:

As you can drag & drop views into different container views (a super cool vscode feature), I put the "Bookmarked Tasks" into my explorer view, so I don't need to keep changing views to run tasks. But as you see in the screenshot below, "Bookmarked Tasks" is not specific enough. I will need to add "Gradle" into the title, but I also want to keep the title short. So I am thinking to change "bookmarked" to "pinned" and change the view titles to:

* Bookmarked Tasks => Pinned Gradle Tasks
* Recent Tasks => Recent Gradle Tasks

That way, if people want to move the views into the explorer, the titles will still make sense. 

I am also considering to add a "Pin" icon/button next to the tasks so you don't need to access the context menu to pin a task, but this will clutter the (already cluttered) recent tasks. So not convinced yet. 

<img width="1552" alt="Screenshot 2020-06-01 at 08 46 24" src="https://user-images.githubusercontent.com/102141/83387538-cae38200-a3e4-11ea-95df-5db6e6a9ed9c.png">

**Comment by hannah23280** [comment]
> As you can drag & drop views into different container views (a super cool vscode feature), I put the "Bookmarked Tasks" into my explorer view, so I don't need to keep changing views to run tasks. But as you see in the screenshot below, "Bookmarked Tasks" is not specific enough. I will need to add "Gradle" into the title, but I also want to keep the title short. So I am thinking to change "bookmarked" to "pinned" and change the view titles to:
> 
> * Bookmarked Tasks => Pinned Gradle Tasks
> * Recent Tasks => Recent Gradle Tasks
> 
> That way, if people want to move the views into the explorer, the titles will still make sense.

Great idea for usability. For the naming,  i saw that you have other views called GRADLE TASKS and GRADLE DAEMONS.  So wonder if you would prefer to follow a standard naming for ease of viewing: e.g to put the "GRADLE" as first word, such as GRADLE PINNED TASKS,  GRADLE  RECENT TASKS,   GRADLE TASKS,  GRADLE DAEMONS

> I am also considering to add a "Pin" icon/button next to the tasks so you don't need to access the context menu to pin a task, but this will clutter the (already cluttered) recent tasks. So not convinced yet.
> 
Previously, I have thought of this idea also , to allow user to quickly add the task to bookmark in a single click. But I ask myself, under what situation will this be helpful. 
My Ans is: When user wanted to bookmark MULTIPLE TASKS. Imagine bookmarking a task required 2 clicks (1 click for right-menu, 1 click to bookmark), hence 10 tasks, 20 clicks.

If that is the case, wonder if it will be better if user can select multiple tasks at a time, and then execute the 2 clicks?  Hence 10 tasks, only 2 clicks.  Cos currently i notice that we can only select one task at a time. Note that this suggestion is only good for choosing multiple tasks with no args. It does not seem make sense for "multiple tasks with args".

Nevertheless, I like the "PIN beside task", and I don't mind the clutterness, hehe.  But of course others might mind.

Alternatively can put the "PIN beside task" on hold first, until enough users requested for it.

**Comment by badsyntax** [comment]
I think let's keep it simple and not clutter the UI. Also pinning multiple tasks creates some problems as you've described, so i won't be looking into that now. 

Whilst I can see your reasoning for the new titles, I think it makes more grammatical sense to go with:

* Gradle Tasks
* Pinned Gradle Tasks
* Recent Gradle Tasks
* Gradle Daemons

**Comment by badsyntax** [comment]
I've released the changes you requested. Note you can disable confirmations with `gradle.disableConfirmations`

**Comment by hannah23280** [comment]
Thanks. Verified successfully, including the gradle.disableConfirmations and the new titles.

**Comment by badsyntax** [comment]
Thanks 👍

**Comment by badsyntax** [comment]
Released with https://github.com/badsyntax/vscode-gradle/releases/tag/3.1.0
