### ISSUE TITLE
Support for wrapper scripts hidden with files.exclude

### ISSUE THREAD

**Issue by badsyntax** [microsoft/vscode-gradle#485]
See: https://github.com/badsyntax/vscode-gradle/issues/135#issuecomment-596236458

**Comment by badsyntax** [comment]
Hi @Drakmyth

I've unable to replicate the issue you posted here: https://github.com/badsyntax/vscode-gradle/issues/135#issuecomment-596236458

I'm using the following to test:

```json
"files.exclude": {
    "**/gradlew": true,
    "**/gradlew.bat": true
}
```

Are you able to confirm this is still an issue for you with the latest version? Thanks!

**Comment by badsyntax** [comment]
Am closing, please re-open if it's still an issue.

**Comment by badsyntax** [comment]
I've been able to replicate, re-opening.

**Comment by Drakmyth** [comment]
> Are you able to confirm this is still an issue for you with the latest version? Thanks!

I was using this plugin on a client project which has since ended, and I don't anticipate doing much Java work in the near future, but if that should change I'll definitely try it out and let you know (though based on your latest comment, seems it's still outstanding).

**Comment by badsyntax** [comment]
I've attempted to replicate this again, unsuccessfully, using vscode 1.47.2. It could be this behaviour was changed in recent vscode versions, although i couldn't find anything to support that.
Going to close as i'm unable to replicate. I can hide the wrapper scripts in the treeview and the extension will still activate.
