### ISSUE TITLE
Reuse terminals for tasks

### ISSUE THREAD

**Issue by dlicois** [microsoft/vscode-gradle#544]
**Is your feature request related to a problem? Please describe.**
Long coding sessions tends to imply many gradle tasks (builds and others). Currently each gradle task opens a new terminal.
This results in many terminals being open, making navigation between gradle tasks and other terminals difficult. While it is possible to delete unused terminals, it requires manual intervention for each one.

**Describe the solution you'd like**
VS code allows a number of customization for presentation behaviour : https://code.visualstudio.com/docs/editor/tasks#_output-behavior
Gradle tasks being volatile, it would be great to make use of these customization options to reuse terminals as much as possible to prevent too many being opened (`presentation.panel` property).

Additionally, consider using `presentation.group` property to allow users to customize terminal panels presentation.

**Describe alternatives you've considered**
Using the output panel [doesn't seem to be a solution.](https://github.com/badsyntax/vscode-gradle/issues/536#issuecomment-648092741).

**Comment by badsyntax** [comment]
Thanks for the feature request. I agree the amount of opened terminals can be overwhelming. The reason it's done this way is to keep task execution history, but I agree there's room for improvement here. 
I'm not entirely sure what the group property results in but I'll have a look. 
Otherwise do you want all tasks to be executed in the same shared terminal, or only tasks with the same name executed in a shared terminal? What would be ideal for you?

**Comment by dlicois** [comment]
Thank you for your great support.

Ideally I would like a single terminal for every gradle tasks as I never really run two gradle tasks at the same time in a single workspace (i don't think it is possible in a single project). But a terminal for each clean and build task would be a great starting point.

I am unsure if it is as simple as switching between `presentation.panel=shared` and `presentation.panel=dedicated`, if so moon shot would be to let users customize the terminal reuse behaviour via an extension property (and even better terminal clear behaviour).

**Comment by badsyntax** [comment]
Making it customizable via extension settings sounds like a good approach. I'll see what I can do :+1:

**Comment by badsyntax** [comment]
I have an initial PR for this here: https://github.com/badsyntax/vscode-gradle/pull/748

This wasn't as easy as using the task options as the task behaviour is different when using a custom vscode.CustomExecution, so i had to manually close previous terminals in the implementation. This means previous task output is lost, but i think this ok.

**Comment by dlicois** [comment]
It's a bit late but I noticed the [Rust extension](https://github.com/rust-lang/vscode-rust) reuse the same terminal for tasks. Maybe it's possible to look at their implementation.

It even has a message saying so
> Terminal will be reused by tasks, press any key to close it.

**Comment by badsyntax** [comment]
Thanks for the link. That extension uses [vscode.ShellExecution](https://github.com/rust-lang/vscode-rust/blob/526556abd1fe981e9827d4b5c533e719fa671377/src/tasks.ts#L42-L46) for the task exeuction, in which case the task terminals can be managed by vscode. 
In my case i'm using [vscode.CustomExecution](https://github.com/badsyntax/vscode-gradle/blob/54a07240b11c62fdec6142e381701d80a5eef36d/extension/src/tasks/taskUtil.ts#L179-L191) with a custom terminal, so i guess vscode can't manage the terminal in the same way. Either way my [implementation](https://github.com/badsyntax/vscode-gradle/pull/748) seems to work pretty well.  You can control the behaviour with:

1 terminal per gradle task:

```json
"gradle.reuseTerminals": "task"
```

1 terminal for all gradle tasks:

```json
"gradle.reuseTerminals": "all"
```

New terminal for every gradle task run:

```json
"gradle.reuseTerminals": "off"
```

I'll release it sometime soon.

**Comment by badsyntax** [comment]
Released with [3.5.0](https://github.com/badsyntax/vscode-gradle/releases/tag/3.5.0). Can you try it out and let me know if there are any issues?

The default behaviour now is only one terminal will be used per task.

**Comment by dlicois** [comment]
I tested all 3 settings and they seem to behave as intended.

Great work. 👍🏻

**Comment by badsyntax** [comment]
Awesome. Thanks for verifying 👍
