### ISSUE TITLE
Support for Inherited Tasks 

### ISSUE THREAD

**Issue by mfreeman-xtivia** [microsoft/vscode-gradle#555]
It would be nice if this plugin could support inherited tasks, i.e. tasks not explicitly defined in the build.gradle file

**Comment by badsyntax** [comment]
Hey, thanks for the feature request. This plugin lists all tasks, even those provided by plugins. Can you give some information as to what an inherited task is?

**Comment by mfreeman-xtivia** [comment]
nm. I missed the requirement for running with a gradle wrapper and the /gradle folder at root of workspace. Seems to work fine once i added that
