### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by psalrod** [microsoft/vscode-gradle#582]
Extension Name: vscode-gradle
Extension Version: dont
![Captura de tela de 2020-07-17 13-49-35](https://user-images.githubusercontent.com/68020691/87788310-120ec080-c835-11ea-971a-a1fd41485ca7.png)
 know
OS Version: Elementary OS 5.1.5
VSCode version: 1.47.2

**Describe the bug**
When debugging during a Run, the error message raize: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

**To Reproduce**
Run with debugging

**Expected behavior**
To complete de Run process and to show the app in the android physical l device

**Screenshots**

**Output from "Gradle Tasks"**
The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=53fffd43-0fd7-4580-ab40-c5eb35d082dc, currentDir=/home/paulo/Documentos/Projetos_Flutter/teste/android}
Attempting to read last messages from the daemon log...
Daemon pid: 13296
  log file: /home/paulo/.gradle/daemon/5.6.2/daemon-13296.out.log
----- Last  20 lines from daemon log file - daemon-13296.out.log -----
11:49:11.941 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 16: received class org.gradle.launcher.daemon.protocol.Build
11:49:11.942 [DEBUG] [org.gradle.launcher.daemon.server.DefaultDaemonConnection] thread 16: Received non-IO message from client: Build{id=53fffd43-0fd7-4580-ab40-c5eb35d082dc, currentDir=/home/paulo/Documentos/Projetos_Flutter/teste/android}
11:49:11.944 [INFO] [org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler] Received command: Build{id=53fffd43-0fd7-4580-ab40-c5eb35d082dc, currentDir=/home/paulo/Documentos/Projetos_Flutter/teste/android}.
11:49:11.945 [DEBUG] [org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler] Starting executing command: Build{id=53fffd43-0fd7-4580-ab40-c5eb35d082dc, currentDir=/home/paulo/Documentos/Projetos_Flutter/teste/android} with connection: socket connection from /0:0:0:0:0:0:0:1:35123 to /0:0:0:0:0:0:0:1:55150.
11:49:11.953 [ERROR] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] Command execution: started DaemonCommandExecution[command = Build{id=53fffd43-0fd7-4580-ab40-c5eb35d082dc, currentDir=/home/paulo/Documentos/Projetos_Flutter/teste/android}, connection = DefaultDaemonConnection: socket connection from /0:0:0:0:0:0:0:1:35123 to /0:0:0:0:0:0:0:1:55150] after 0.0 minutes of idle
11:49:11.954 [INFO] [org.gradle.launcher.daemon.server.DaemonRegistryUpdater] Marking the daemon as busy, address: [4cbe81a2-893b-4789-a0e2-2b6a38896f9b port:35123, addresses:[/0:0:0:0:0:0:0:1%lo, /127.0.0.1]]
11:49:11.954 [DEBUG] [org.gradle.launcher.daemon.registry.PersistentDaemonRegistry] Marking busy by address: [4cbe81a2-893b-4789-a0e2-2b6a38896f9b port:35123, addresses:[/0:0:0:0:0:0:0:1%lo, /127.0.0.1]]
11:49:11.956 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire exclusive lock on daemon addresses registry.
11:49:11.959 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
11:49:11.963 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
11:49:11.964 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] resetting idle timer
11:49:11.965 [DEBUG] [org.gradle.launcher.daemon.server.DaemonStateCoordinator] daemon is running. Sleeping until state changes.
11:49:11.967 [INFO] [org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy] Daemon is about to start building Build{id=53fffd43-0fd7-4580-ab40-c5eb35d082dc, currentDir=/home/paulo/Documentos/Projetos_Flutter/teste/android}. Dispatching build started information...
11:49:11.969 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 18: dispatching class org.gradle.launcher.daemon.protocol.BuildStarted
11:49:11.986 [DEBUG] [org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment] Configuring env variables: {PATH=/home/paulo/.local/bin:/usr/lib/jvm/java-oracle//bin:/home/paulo/.local/bin:/usr/lib/jvm/java-oracle//bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:~/Flutter/flutter/bin:~/Flutter/flutter/bin/cache/dar-sdk/bin:~/Flutter/flutter/bin/cache/dart-sdk/bin:~/Flutter/flutter/bin:~/Flutter/flutter/bin:~/Flutter/flutter/bin/cache/dar-sdk/bin:/home/paulo/Documentos/Projetos_Flutter/flutter/bin:/home/paulo/Flutter/bin/cache:~/Flutter/flutter/bin/cache/dart-sdk/bin:~/Flutter/flutter/bin, XAUTHORITY=/home/paulo/.Xauthority, FLUTTER_HOST=VSCode, LC_MEASUREMENT=pt_PT.UTF-8, LC_TELEPHONE=pt_PT.UTF-8, XMODIFIERS=@im=ibus, GDMSESSION=pantheon, XDG_DATA_DIRS=/usr/share/gnome:/usr/share/pantheon:/home/paulo/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share, MANDATORY_PATH=/usr/share/gconf/pantheon.mandatory.path, LC_TIME=pt_PT.UTF-8, VSCODE_LOG_STACK=false, PUB_ENVIRONMENT=vscode.dart-code, DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus, VSCODE_PID=11404, DEFAULTS_PATH=/usr/share/gconf/pantheon.default.path, XDG_CURRENT_DESKTOP=Unity, SSH_AGENT_PID=1232, SESSION_MANAGER=local/Samsung:@/tmp/.ICE-unix/1104,unix/Samsung:/tmp/.ICE-unix/1104, LC_PAPER=pt_PT.UTF-8, LOGNAME=paulo, APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL=true, PWD=/home/paulo/Documentos/Projetos_Flutter/teste/android, VSCODE_NLS_CONFIG={"locale":"pt-br","availableLanguages":{},"_languagePackSupport":
11:49:11.986 [DEBUG] [org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment] Configuring env variables: {PATH=/home/paulo/.local/bin:/usr/lib/jvm/java-oracle//bin:/home/paulo/.local/bin:/usr/lib/jvm/java-oracle//bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:~/Flutter/flutter/bin:~/Flutter/flutter/bin/cache/dar-sdk/bin:~/Flutter/flutter/bin/cache/dart-sdk/bin:~/Flutter/flutter/bin:~/Flutter/flutter/bin:~/Flutter/flutter/bin/cache/dar-sdk/bin:/home/paulo/Documentos/Projetos_Flutter/flutter/bin:/home/paulo/Flutter/bin/cache:~/Flutter/flutter/bin/cache/dart-sdk/bin:~/Flutter/flutter/bin, XAUTHORITY=/home/paulo/.Xauthority, FLUTTER_HOST=VSCode, LC_MEASUREMENT=pt_PT.UTF-8, LC_TELEPHONE=pt_PT.UTF-8, XMODIFIERS=@im=ibus, GDMSESSION=pantheon, XDG_DATA_DIRS=/usr/share/gnome:/usr/share/pantheon:/home/paulo/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share, MANDATORY_PATH=/usr/share/gconf/pantheon.mandatory.path, LC_TIME=pt_PT.UTF-8, VSCODE_LOG_STACK=false, PUB_ENVIRONMENT=vscode.dart-code, DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus, VSCODE_PID=11404, DEFAULTS_PATH=/usr/share/gconf/pantheon.default.path, XDG_CURRENT_DESKTOP=Unity, SSH_AGENT_PID=1232, SESSION_MANAGER=local/Samsung:@/tmp/.ICE-unix/1104,unix/Samsung:/tmp/.ICE-unix/1104, LC_PAPER=pt_PT.UTF-8, LOGNAME=paulo, APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL=true, PWD=/home/paulo/Documentos/Projetos_Flutter/teste/android, VSCODE_NLS_CONFIG={"locale":"pt-br","availableLanguages":{},"_languagePackSupport":true}, AMD_ENTRYPOINT=vs/workbench/services/extensions/node/extensionHostProcess, LANGUAGE=pt_BR:pt:en, LESSOPEN=| /usr/bin/lesspipe %s, SHELL=/bin/bash, CHROME_DESKTOP=code-url-handler.desktop, LC_ADDRESS=pt_PT.UTF-8, GIO_LAUNCHED_DESKTOP_FILE=/usr/share/applications/code.desktop, OLDPWD=/home/paulo/Documentos/Projetos_Flutter/teste/android, GNOME_DESKTOP_SESSION_ID=this-is-deprecated, ORIGINAL_XDG_CURRENT_DESKTOP=Pantheon, GTK_MODULES=gail:atk-bridge, VSCODE_NODE_CACHED_DATA_DIR=/home/paulo/.config/Code/CachedData/17299e413d5590b14ab0340ea477cdd86ff13daf, XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0, VERBOSE_LOGGING=true, XDG_SESSION_DESKTOP=pantheon, LS_COLORS=, SHLVL=2, LC_IDENTIFICATION=pt_PT.UTF-8, LC_MONETARY=pt_PT.UTF-8, LESSCLOSE=/usr/bin/lesspipe %s %s, VSCODE_HANDLES_UNCAUGHT_ERRORS=true, QT_IM_MODULE=ibus, JAVA_HOME=/opt/android-studio/jre, FLUTTER_ROOT=/home/paulo/Flutter/flutter, XDG_CONFIG_DIRS=/etc/xdg/xdg-pantheon:/etc/xdg, XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0, LANG=pt_BR.UTF-8, XDG_SESSION_TYPE=x11, XDG_SESSION_ID=c2, PIPE_LOGGING=true, QT_STYLE_OVERRIDE=adwaita, DISPLAY=:0, ELECTRON_RUN_AS_NODE=1, LC_NAME=pt_PT.UTF-8, VSCODE_IPC_HOOK_EXTHOST=/tmp/vscode-ipc-8ac20411-9c65-45e7-9bd0-1d803d523e8a.sock, FLUTTER_SUPPRESS_ANALYTICS=true, GDM_LANG=pt_BR, GTK3_MODULES=pantheon-filechooser-module:pantheon-filechooser-module, XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/paulo, GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1, DESKTOP_SESSION=pantheon, VSCODE_LOGS=/home/paulo/.config/Code/logs/20200717T113008, USER=paulo, CLASSPATH=/home/paulo/Documentos/Projetos_Flutter/teste/android/gradle/wrapper/gradle-wrapper.jar, GTK_CSD=1, XDG_MENU_PREFIX=gnome-, GIO_LAUNCHED_DESKTOP_FILE_PID=11404, QT_ACCESSIBILITY=1, LC_NUMERIC=pt_PT.UTF-8, XDG_SEAT=seat0, SSH_AUTH_SOCK=/run/user/1000/keyring/ssh, FLUTTER_ALREADY_LOCKED=true, QT_QPA_PLATFORMTHEME=gtk3, XDG_RUNTIME_DIR=/run/user/1000, XDG_VTNR=7, HOME=/home/paulo, VSCODE_IPC_HOOK=/run/user/1000/vscode-132e047d-1.47.2-main.sock}
11:49:12.013 [DEBUG] [org.gradle.launcher.daemon.server.exec.LogToClient] About to start relaying all logs to the client via the connection.
11:49:12.014 [INFO] [org.gradle.launcher.daemon.server.exec.LogToClient] The client will now receive all logging from the daemon (pid: 13296). The daemon log file: /home/paulo/.gradle/daemon/5.6.2/daemon-13296.out.log
11:49:12.022 [INFO] [org.gradle.launcher.daemon.server.exec.LogAndCheckHealth] Starting build in new daemon [memory: 1,4 GB]
11:49:12.060 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] The daemon has started executing the build.
11:49:12.063 [DEBUG] [org.gradle.launcher.daemon.server.exec.ExecuteBuild] Executing build with daemon context: DefaultDaemonContext[uid=f3ad245a-a505-4c1a-a5d4-6766a9ed884b,javaHome=/opt/android-studio/jre,daemonRegistryDir=/home/paulo/.gradle/daemon,pid=13296,idleTimeout=10800000,priority=NORMAL,daemonOpts=-Xmx1536M,-Dfile.encoding=UTF-8,-Duser.country=BR,-Duser.language=pt,-Duser.variant]
----- End of the daemon log -----

FAILURE: Build failed with an exception.

* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Does the bug still exist if you disable all other extensions?**
Yes/No

**Additional context**

**Comment by psalrod** [comment]
UPDATE:
Problem solved. It was a syntax error on my code. I was using VSCode.
I had the same problem with gradle when using Android Studio with other project and I found a syntax error.
I corrected the mistake on the code and the gradle error disappeared.

I did a verification on my project in VSCode and the problem also disappeared.

**Comment by badsyntax** [comment]
👍
