### ISSUE TITLE
Gradle JVM should use the java.import.gradle.java.home from vscode-java

### ISSUE THREAD

**Issue by qzmarco** [microsoft/vscode-gradle#588]
Hi guys!

I have updated my vscode-java extension and now I am not able to run Gradle Daemon so good. I am using some older Gradle versions that requires JVM 8 and vscode-gradle is using the JVM set at "java.home", but now, in version 0.65 from vscode-java, there is an optional called "java.import.gradle.java.home" when I set which VM will be used to run the Gradle Daemon.

Is it possible to be corrected?

[https://github.com/redhat-developer/vscode-java/issues/1536](url)

**Comment by badsyntax** [comment]
Thanks for the report. Ok I will adjust the behaviour so that the `java.import.gradle.java.home` takes precedence over `java.home` when launching the Gradle server.

**Comment by badsyntax** [comment]
Released with [3.4.0](https://github.com/badsyntax/vscode-gradle/releases/tag/3.4.0). Can you update the extension and test this change? Thanks.

**Comment by qzmarco** [comment]
3.4.0 and 3.4.1 are perfect! Thank you very much!

**Comment by badsyntax** [comment]
Great, thanks for verifying.
