### ISSUE TITLE
Publish extension to Open VSX Registry

### ISSUE THREAD

**Issue by ebramirez** [microsoft/vscode-gradle#679]
**Is your feature request related to a problem? Please describe.**
Other IDEs based on Eclipse Theia (The engine behind VS Code) like VSCodium, Eclipse Che, GitPod, etc, use [Open VSX Registry](https://open-vsx.org) instead of the proprietary VS Code Marketplace, so this plugin is not available for those using them.

**Describe the solution you'd like**
I would like that the plugin is deployed to the Open VSX Registry upon release, like it is currently done for the VS Code Marketplace.

The procedure is documented [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by badsyntax** [comment]
Thanks for the issue report. I will setup the publish workflow in my CI/CD when I get a bit of time. I'd like to review the registry and tooling first.
Can I ask, is it true to say Eclipse Theia is the engine behind vscode? Does that imply vscode uses Theia?

**Comment by ebramirez** [comment]
> Thanks for the issue report. I will setup the publish workflow in my CI/CD when I get a bit of time. I'd like to review the registry and tooling first.

Thank you, that would be great.

> Can I ask, is it true to say Eclipse Theia is the engine behind vscode? Does that imply vscode uses Theia?

Technically, vscode does not use Theia. Theia is the result of extracting the editor part from vscode and making it usable through a pure web interface additionally to the local editor.

**Comment by badsyntax** [comment]
This extension will now be published to open-vsx for every release. I requested namespace ownership here: https://github.com/eclipse/open-vsx.org/issues/141

**Comment by ebramirez** [comment]
Thanks!
