### ISSUE TITLE
Gradle tasks don't load when windows username has a space in

### ISSUE THREAD

**Issue by NickHeap2** [microsoft/vscode-gradle#680]
Extension Name: vscode-gradle
Extension Version: 3.4.2
OS Version: Windows 10
VSCode version: 1.48.2

**Describe the bug**
Gradle tasks don't load when windows username has a space in.

**To Reproduce**
Have a username with a space in it.
Gradle user home is "C:\Users\Nick Heap\\.gradle".
Open Gradle view.
Errors will appear in the Gradle Tasks output view showing that server command stops at space in name and no tasks will be found.

**Expected behavior**
Gradle tasks should be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/42422453/92331419-574db280-f06e-11ea-941f-7f71eb23fd23.png)

**Output from "Gradle Tasks"**
[info] [gradle-server] 'c:\Users\Nick' is not recognized as an internal or external command,
operable program or batch file.
[warn] [gradle-server] Gradle server stopped
[info] [gradle-server] 'c:\Users\Nick' is not recognized as an internal or external command,
operable program or batch file.
[warn] [gradle-server] Gradle server stopped
[info] [gradle-server] 'c:\Users\Nick' is not recognized as an internal or external command,
operable program or batch file.
[warn] [gradle-server] Gradle server stopped
[info] [gradle-server] 'c:\Users\Nick' is not recognized as an internal or external command,
operable program or batch file.
[warn] [gradle-server] Gradle server stopped
[error] Error connecting to gradle server: Failed to connect before the deadline
[error] Error connecting to gradle server: Failed to connect before the deadline
[error] Error connecting to gradle server: Failed to connect before the deadline
[error] Error connecting to gradle server: Failed to connect before the deadline

**Does the bug still exist if you disable all other extensions?**
Yes

**Comment by NickHeap2** [comment]
It looks like it is because the server batch file is in an extenstion install directory with a space in "C:\Users\Nick Heap\.vscode\extensions\richardwillis.vscode-gradle-3.4.2\lib\gradle-server.bat".

**Comment by NickHeap2** [comment]
Debug output:
[debug] [gradle-server] Starting server
[debug] [gradle-server] Gradle Server cmd: c:\Users\Nick Heap\.vscode\extensions\richardwillis.vscode-gradle-3.4.2\lib\gradle-server.bat 54479
[info] [gradle-server] 'c:\Users\Nick' is not recognized as an internal or external command,
operable program or batch file.
[warn] [gradle-server] Gradle server stopped
[error] Error connecting to gradle server: Failed to connect before the deadline
[error] Error connecting to gradle server: Failed to connect before the deadline

**Comment by NickHeap2** [comment]
Looks like this is already fixed in master :)

**Comment by badsyntax** [comment]
Hi, thanks for reporting this issue. Indeed this issue has been solved in master but i forgot to release! I have now released this fix with [3.4.3](https://github.com/badsyntax/vscode-gradle/releases/tag/3.4.3). 

Can you let me know if it's fixed for you?

**Comment by NickHeap2** [comment]
Yes all working great thanks :)
