### ISSUE TITLE
Plugin Gradle Server processes remaining after vscode is closed

### ISSUE THREAD

**Issue by RobMaskell** [microsoft/vscode-gradle#684]
Extension Name: vscode-gradle
Extension Version: 3.4.3
OS Version: 
`Linux pop-os 5.4.0-7642-generic #46~1597422484~20.04~e78f762-Ubuntu SMP  x86_64 x86_64 x86_64 GNU/Linux`

VSCode version: 1.48.2

**Describe the bug**
After a day or two of use of vscode and the gradle plugin and with vscode closed these are the remaining java processes
```
ps -eo pid,size,lstart,cmd | grep [j]ava
 126096 334316 Tue Sep  8 01:43:29 2020 java -classpath /home/robm/.vscode/extensions/richardwillis.vscode-gradle-3.4.2/lib/gradle-server.jar com.github.badsyntax.gradle.GradleServer 39889
 131382 329264 Tue Sep  8 05:10:22 2020 java -classpath /home/robm/.vscode/extensions/richardwillis.vscode-gradle-3.4.2/lib/gradle-server.jar com.github.badsyntax.gradle.GradleServer 45555
 131896 299340 Tue Sep  8 05:11:15 2020 java -classpath /home/robm/.vscode/extensions/richardwillis.vscode-gradle-3.4.2/lib/gradle-server.jar com.github.badsyntax.gradle.GradleServer 40099
 132182 299236 Tue Sep  8 05:11:44 2020 java -classpath /home/robm/.vscode/extensions/richardwillis.vscode-gradle-3.4.2/lib/gradle-server.jar com.github.badsyntax.gradle.GradleServer 40401
 134179 321380 Tue Sep  8 05:33:00 2020 java -classpath /home/robm/.vscode/extensions/richardwillis.vscode-gradle-3.4.2/lib/gradle-server.jar com.github.badsyntax.gradle.GradleServer 38377
 141480 327428 Tue Sep  8 10:09:22 2020 java -classpath /home/robm/.vscode/extensions/richardwillis.vscode-gradle-3.4.2/lib/gradle-server.jar com.github.badsyntax.gradle.GradleServer 45445
 141924 396312 Tue Sep  8 10:09:57 2020 java -classpath /home/robm/.vscode/extensions/richardwillis.vscode-gradle-3.4.2/lib/gradle-server.jar com.github.badsyntax.gradle.GradleServer 34225
 149198 776944 Tue Sep  8 12:02:40 2020 /usr/lib/jvm/java-11-openjdk-amd64/bin/java --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -Xms256m -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=GB -Duser.language=en -Duser.variant -cp /home/robm/.gradle/wrapper/dists/gradle-6.4.1-bin/33549z180oh3o1s64iwo25l48/gradle-6.4.1/lib/gradle-launcher-6.4.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.4.1
 163953 289752 Tue Sep  8 14:27:07 2020 java -classpath /home/robm/.vscode/extensions/richardwillis.vscode-gradle-3.4.3/lib/gradle-server.jar com.github.badsyntax.gradle.GradleServer 45947
```
The Daemon process may close in time but this bug is related to the GradleServer processes that seem to be hanging around.

**To Reproduce**
I'm running linux in a vmware VM on the latest MacOS
Close vscode
run `killall --user robm java` or similar to kill off all the java processes listed above
Open vscode project that is spring boot / gradle based but no need to run it just wait for spinning to stop
Close vscode, this is the list of java processes
```
ps -eo pid,size,lstart,cmd | grep [j]ava
 169048 327060 Tue Sep  8 17:18:12 2020 java -classpath /home/robm/.vscode/extensions/richardwillis.vscode-gradle-3.4.3/lib/gradle-server.jar com.github.badsyntax.gradle.GradleServer 32969
 169268 522312 Tue Sep  8 17:18:22 2020 /usr/lib/jvm/java-11-openjdk-amd64/bin/java --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -Xms256m -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=GB -Duser.language=en -Duser.variant -cp /home/robm/.gradle/wrapper/dists/gradle-6.4.1-bin/33549z180oh3o1s64iwo25l48/gradle-6.4.1/lib/gradle-launcher-6.4.1.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 6.4.1
```

**Expected behavior**
I understand why I would have the gradle daemon after closing vscode but I expected the Gradle Server process to close with vscode. I seem to get one new Gradle Server process each time I open and close vscode

**Comment by RobMaskell** [comment]
In case it makes a difference I'm running vscode `Node runtime not found. Using default as a fallback.` and the project is part of a workspace.

I've tried two different spring boot / gradle projects one more complex one and a very simple one, same result.

**Comment by badsyntax** [comment]
Thanks for the detailed issue report, much appreciated! 

To outline how the server process is terminated, whenever vscode is closed or when the extension is disabled or uninstalled:

1. VS Code will call the [dispose method](https://github.com/EzraEn1/vscode-gradle/blob/45ad371e6d0c93c7d77cf0781593f09d71d660b6/extension/src/server/GradleServer.ts#L127-L132) which: 
2. [calls killProcess](https://github.com/EzraEn1/vscode-gradle/blob/45ad371e6d0c93c7d77cf0781593f09d71d660b6/extension/src/server/GradleServer.ts#L129) which: 
3. [sends a SIGTERM](https://github.com/EzraEn1/vscode-gradle/blob/45ad371e6d0c93c7d77cf0781593f09d71d660b6/extension/src/server/GradleServer.ts#L115) signal to the process to kill it

Couple of points:

- `SIGTERM` seems the most appropriate signal, to allow the java server to gracefully shutdown, but doesn't guarantee the process will be killed (see `SIGKILL`). 
- I'm not checking the return value when calling `process.kill()`. I should first try [kill the process](https://nodejs.org/api/child_process.html#child_process_subprocess_kill_signal) with `SIGTERM` and if unsuccessful then try `SIGKILL`

Am downloading a linux VM to try reproduce, will hopefully get a fix out soon.

**Comment by RobMaskell** [comment]
Interesting and also weird as I can execute `kill <pid>` which will get rid of these gradle server processes and apparently the default for `kill` is `SIGTERM`

**Comment by badsyntax** [comment]
After a bit of pain of getting VirtualBox to play nice with Ubuntu, i've now replicated the issue. Will try get a fix out over the weekend.

**Comment by badsyntax** [comment]
I've released a fix with [3.4.4](https://github.com/badsyntax/vscode-gradle/releases/tag/3.4.4). Can you test this change?

**Comment by RobMaskell** [comment]
Thanks, I'll take a look now

**Comment by RobMaskell** [comment]
Yup that works for me, no gradle server processes after vscode closed. Seems to clear out the gradle daemons as well as I don't see them hanging around either

**Comment by badsyntax** [comment]
I didn't notice this at the time, but you're right. For me, on MacOS, i can open multiple vscode windows and spawn a bunch of different java processes and kill them all (daemons & server) by closing vscode.
It's confuses me a bit as it's supposed to behave the same as using the wrapper script, and for me running `./gradlew build` will leave a daemon running. I guess i'm killing too many sub-processes, but this is actually a pretty useful side effect as people have complained about the hanging daemon processes.
