### ISSUE TITLE
Local Gradle wrapper executables must exist at the root of the workspace folders?

### ISSUE THREAD

**Issue by hannah23280** [microsoft/vscode-gradle#717]
vscode-gradle extensions: v3.4.5

Hi, 
     I notice that one of the requirement for the extension to work is "Local Gradle wrapper executables must exist at the root of the workspace folders".   As shown in the screenshot, the gradlew.bat is not at the root of the workspace (Tutorial1 folder), but at the root of the subfolder called demoMS1.  Can i check that vscode-gradle extension will not support such workspace configuration?

![image](https://user-images.githubusercontent.com/4410920/94545832-a5c22b80-027f-11eb-9d6a-3c5e277cb294.png)

**Comment by hannah23280** [comment]
please ignore my query. I misunderstand the meaning of "Local Gradle wrapper executables must exist at the root of the workspace folders".

**Comment by badsyntax** [comment]
Btw this extension does support nested projects, you just need to enable that feature with the setting "gradle.nestedProjects".

**Comment by hannah23280** [comment]
> Btw this extension does support nested projects, you just need to enable that feature with the setting "gradle.nestedProjects".
Thanks! Never know have such setting.

**Comment by badsyntax** [comment]
here's some reasoning as to why it's not enabled by default: https://github.com/badsyntax/vscode-gradle/issues/339#issuecomment-624597238

**Comment by hannah23280** [comment]
> here's some reasoning as to why it's not enabled by default: [#339 (comment)](https://github.com/badsyntax/vscode-gradle/issues/339#issuecomment-624597238)

Noted. Thanks.  But regardless of whether nested projects are enabled or not, the folder added to the workspace must contain a build.gradle file.  In order word, I can't add a folder A to the workspace, in which folder A does not have build.gradle, even if its subfolder folder B has. Not sure if my understanding is correct.

**Comment by badsyntax** [comment]
> But regardless of whether nested projects are enabled or not, the folder added to the workspace must contain a build.gradle file.

if `"gradle.nestedProjects": true`, the folder added to the workspace does not need to contain any gradle build files.

Consider the following directory tree:

```
─── projecta
    └── projectb
        ├── build.gradle
        └── gradlew
```

If I open `projecta` with ``"gradle.nestedProjects": false``, then the extension won't load the gradle projectb.

If I open `projecta` with ``"gradle.nestedProjects": true``, then the extension will load the gradle projectb.

(To clarify, gradle project discovery is based on the wrapper scripts not the build.gradle files [as gradle projects can have multiple nested build.gradle files])

I think I need to update the README to make this more obvious. The following doesn't reflect what i've mentioned:

> Local Gradle wrapper executables must exist at the root of the workspace folders

It should rather say something like:

> Local Gradle wrapper executables must exist at the root of the Gradle projects

I'm going to re-open this ticket for tracking purposes.

**Comment by badsyntax** [comment]
I've updated the [README](https://github.com/badsyntax/vscode-gradle/blob/master/README.md). Hopefully it's a little clearer.

**Comment by hannah23280** [comment]
Thanks for updating the README to improve clarity.
I just come to realize i have misinterpret the meaning of gradle.nestedProjects.  I initially still thought nestedProjects refer to multi-project gradle where we have a root gradle project with one or more nested child gradle project. Then now i realize these are 2 different things. But now i get it that the "nestedProjects" means gradle projects that are nested inside the root folder, such that once this setting is set to true, the root folder no longer  need to have the local gradle wrapper executable. 

Since we are on the topic of gradle.nestedProjects, just to highlight to you in my vscode IDE, i saw that there is no description for the gradle.nestedProjects (see screenshot), but other settings have.

![image](https://user-images.githubusercontent.com/4410920/95535304-af375a80-0a1a-11eb-93fc-d46a11ab973b.png)

**Comment by badsyntax** [comment]
Yes that's all correct.

Thanks for pointing out the missing description, i am fixing that with https://github.com/badsyntax/vscode-gradle/pull/745
