### ISSUE TITLE
Single-clicking on a gradle task open the build.gradle file unintentionally

### ISSUE THREAD

**Issue by hannah23280** [microsoft/vscode-gradle#718]
Extension Name: vscode-gradle
Extension Version: 3.4.5
OS Version: Windows 10
VSCode version: 1.49.2

I not sure if it was meant to work in that way. Whenever i single-click on a gradle task in the "Gradle Tasks" pane , the build.gradle file will keep opening, and as a result, I have to keep switching back to my source code or have to close the build.gradle.

I thought double-clicking on the gradle task to open the build.gradle would be sufficient. Single-click should not open the file, cos it is too easy for the developer to accidentally single click on any of the gradle task, and hence open the build.gradle unintentionally.

**Comment by badsyntax** [comment]
Thanks for report. It's intentional, but I agree it's not a good user experience. I have found myself in the same scenario. I will change it to use double-click and add maybe add this option to the context menu too.

**Comment by badsyntax** [comment]
I've released this change with [3.4.6](https://github.com/badsyntax/vscode-gradle/releases/tag/3.4.6). Can you try it out? The changes are:

- Only open build file on double click
- Add context menu item to open build file

**Comment by hannah23280** [comment]
> I've released this change with [3.4.6](https://github.com/badsyntax/vscode-gradle/releases/tag/3.4.6). Can you try it out? The changes are:
> 
> * Only open build file on double click
> * Add context menu item to open build file

Thanks for the quick change. Tested both scenario, work successfully!
