### ISSUE TITLE
Installing version 3.5.0 directly through the kotlin development pack didn't activate this extension

### ISSUE THREAD

**Issue by zrno** [microsoft/vscode-gradle#757]
Issue Type: <b>Bug</b>

Installed Kotlin development pack https://marketplace.visualstudio.com/items?itemName=sethjones.kotlin-on-vscode
Gradle task extension doesn't show up and is not activated. The command "View: Show gradle" is avaialable but doesn't do anything.
To make it work I had to install an older version, I randomly choose 3.4.3 and it started working after a reload. After that I could install the latest version 3.5.0 and it continued to work properly

Extension version: 3.5.0
VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1240 v6 @ 3.70GHz (8 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (3.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by badsyntax** [comment]
Thanks for the issue report, i'll look into this.

**Comment by badsyntax** [comment]
I'm not able to replicate this. It might have been a temporary conflict with another extension. If you're able to replicate this again, can you paste the output from the "Gradle Tasks" output channel?

**Comment by zrno** [comment]
Wasn't able to replicate this again. Not sure what happened. Will close for now
