### ISSUE TITLE
Build Task in the root gradle project does not get displayed

### ISSUE THREAD

**Issue by hannah23280** [microsoft/vscode-gradle#794]
Extension Name: vscode-gradle
Extension Version: 3.5.2
OS Version:Windows
VSCode version: 1.51.1

**Describe the bug**
I am developing a gradle-based project, which has nested gradle projects (namely, mainservice and mainservice1), as shown in the below screenshot.  I notice that the root gradle project (csv_bundler) does not have a task called build. But yet, i can go to the command prompt and execute gradlew.bat build at the root project.  

![image](https://user-images.githubusercontent.com/4410920/99880431-36006980-2c4e-11eb-96f3-e2ae39fe17ee.png)

When i execute the gradlew.bat tasks at the root project, the terminal list down all the supported tasks , one of them include build task. But yet  in the gradle pane, build task (among others) does not get displayed.
![image](https://user-images.githubusercontent.com/4410920/99880376-f5085500-2c4d-11eb-948f-cd3af4f38db4.png)

**Comment by hannah23280** [comment]
My goal is to execute build task at root gradle project, so as to trigger build task for all the nested child projects. I can do it via terminal manual typing, but could not do it via gradle pane

**Comment by badsyntax** [comment]
Thanks for the report. I can reproduce on a clean project using `gradle init`. Seems like the Gradle API won't return root runnable tasks if there's no corresponding `build.gradle` file for root. Not sure why, but i'll investigate. 

(Although not ideal, you can still run root tasks using the "Run a Gradle Build" feature, by clicking on the Terminal icon)

**Comment by hannah23280** [comment]
> Thanks for the report. I can reproduce on a clean project using `gradle init`. Seems like the Gradle API won't return root runnable tasks if there's no corresponding `build.gradle` file for root. Not sure why, but i'll investigate.
> 
> (Although not ideal, you can still run root tasks using the "Run a Gradle Build" feature, by clicking on the Terminal icon)

Noted. For your info, my root workspace folder has a build.gradle, and is the parent of the nested gradle projects called main-service and main-service1

**Comment by hannah23280** [comment]
Just for your reference, Intellij displays the circled task at the root gradle project. But the vscode-gradle does not display them

![image](https://user-images.githubusercontent.com/4410920/100455451-af3e0780-30f9-11eb-9f80-bb64f4f90559.png)

**Comment by badsyntax** [comment]
I've not seeing root "default" tasks when I run `./gradlew tasks --all`. I don't know what gradle api I should be using to discover those tasks. I'm currently using [getTasks](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/GradleBuild.html#getTasks--) but it's not listing these "default" tasks. 

They seem like special case tasks that are internal to gradle.

 I wish I knew how intellij is discovering those tasks!

**Comment by hannah23280** [comment]
> I've not seeing root "default" tasks when I run `./gradlew tasks --all`. I don't know what gradle api I should be using to discover those tasks. I'm currently using [getTasks](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/GradleBuild.html#getTasks--) but it's not listing these "default" tasks.
> 
> They seem like special case tasks that are internal to gradle.
> 
> I wish I knew how intellij is discovering those tasks!

Hi,
I tried  run  ./gradlew tasks (without the --all) in the root. It is able to discover those tasks (e.g  root's build task).
I try asking gradle engineer to see if they have any idea what api to call.

**Comment by hannah23280** [comment]
meanwhile, have u tried getAllTasks api?

**Comment by hannah23280** [comment]
Bump

**Comment by badsyntax** [comment]
hi @hanct. fyi the project has been transferred to Microsoft and i'm no longer doing active development on it. i'm sure the MS devs will eventually pick this up, but they probably aren't getting notified in these old issues.

**Comment by hannah23280** [comment]
> hi @hanct. fyi the project has been transferred to Microsoft and i'm no longer doing active development on it. i'm sure the MS devs will eventually pick this up, but they probably aren't getting notified in these old issues.

Understood. Thanks.  I will open another new request again.   Thanks for helping to maintain this great extension all these while.

**Comment by CsCherrYY** [comment]
closed in #1046
