### ISSUE TITLE
Extension icon doesn't appear

### ISSUE THREAD

**Issue by jdomag** [microsoft/vscode-gradle#796]
Extension Name: vscode-gradle
Extension Version: 3.5.2
OS Version: fedora 32
VSCode version: 1.51.1

**Describe the bug**
After installation of Gradle Task plugin, plugin icon doesn't appear on the left hand side panel and I can't use the extension. Output console doesn't show "gradle tasks" on the list.

**To Reproduce**
N/A

**Screenshots**

![DeepinScreenshot_select-area_20201124213050](https://user-images.githubusercontent.com/28705876/100148397-0004f480-2e9d-11eb-91ef-b33e3c7e726e.png)

**Output from "Gradle Tasks"**
No gradle tasks on the output list.

**Does the bug still exist if you disable all other extensions?**
Yes

**Additional context**

**Comment by badsyntax** [comment]
Do gradle wrapper executables exist at the root of the project? (`gradlew` or `gradlew.bat`)

**Comment by jdomag** [comment]
thanks, i missed that I need to execute "gradle wrapper" first.
