### ISSUE TITLE
gradle version inconsistence

### ISSUE THREAD

**Issue by wxlfrank** [microsoft/vscode-gradle#797]
Extension Name: vscode-gradle
Extension Version: v3.5.2
OS Version: macOS Big Sur Version 11.0.1
VSCode version: 1.51.1

**Describe the bug**
I installed gradle 6.7 and use gradle init to create a gradle project
but in vscode, the .gradle folder contains both 6.3 and 6.7 subfolders.

If I run the gradle init command in terminal, there is only one subfoler, 6.7, in the .gradle folder

I also found in the buildOutputCleanup folder, the cache.properties file has gradle.version=6.3
where does this gradle.version property come from?

**To Reproduce**
- mkdir test && cd test
- gradle init
- code .

**Expected behavior**
gradle project should has no problem in vscode

**Comment by wxlfrank** [comment]
the current gradle task setting is 

	// Arguments to pass to Gradle.
	"java.import.gradle.arguments": null,

	// Enable/disable the Gradle importer.
	"java.import.gradle.enabled": true,

	// Use Gradle from the specified local installation directory or GRADLE_HOME if the Gradle wrapper is missing or disabled and no 'java.import.gradle.version' is specified.
	"java.import.gradle.home": null,

	// The location to the JVM used to run the Gradle daemon.
	"java.import.gradle.java.home": null,

	// JVM arguments to pass to Gradle.
	"java.import.gradle.jvmArguments": null,

	// Enable/disable the Gradle offline mode.
	"java.import.gradle.offline.enabled": false,

	// Setting for GRADLE_USER_HOME.
	"java.import.gradle.user.home": null,

	// Use Gradle from the specific version if the Gradle wrapper is missing or disabled.
	"java.import.gradle.version": null,

	// Use Gradle from the 'gradle-wrapper.properties' file.
	"java.import.gradle.wrapper.enabled": true,

	// Enable/disable the Maven importer.
	"java.import.maven.enabled": true,

	// Defines allowed/disallowed SHA-256 checksums of Gradle Wrappers
	"java.imports.gradle.wrapper.checksums": [],

**Comment by badsyntax** [comment]
Unfortunately I cannot reproduce. I can init a new project using gradle 6.7.1 and that's the version used in vscode. 

Can you paste the contents of `gradle/wrapper/gradle-wrapper.properties`? 

Can you also paste the output from the `Gradle Tasks` extension? (You can find these logs in the `Output` panel).

**Comment by wxlfrank** [comment]
as your request.

gradle/wrapper/gradle-wrapper.properties
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

Gradle Tasks output
```
[info] [gradle-server] Server started, listening on 59777
[info] Gradle client connected to server
[info] Java Home: /Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home
[info] JVM Args: --add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=NO,-Duser.language=en,-Duser.variant
[info] Gradle User Home: /Users/wxlfrank/.gradle
[info] Gradle Version: 6.7
[info] CONFIGURE SUCCESSFUL in 143ms
[info] Found 46 tasks
```

**Comment by wxlfrank** [comment]
Another action should be done to reproduce the problem.

open the main java file, the .gradle folder will be updated

**Comment by badsyntax** [comment]
Hmm, i wonder if it's the Java extension doing this. Possibly related issue: https://github.com/redhat-developer/vscode-java/issues/924

Can you try disable the Java extension and test this again?

**Comment by wxlfrank** [comment]
Yes. You are right. Thank you for the help
