### ISSUE TITLE
Is there any way to run/debug a task multiple times

### ISSUE THREAD

**Issue by hannah23280** [microsoft/vscode-gradle#798]
In view of current trend towards cloud and microservice, developer might need to run multiple instances of  the same microservice application in the development machine to simulate replicas, can the vscode-gradle allow us to execute a gradle task (say run) multiple times in order to get multiple instances of the same application running

**Comment by hannah23280** [comment]
Currently, when i execute a task to run the application via vscode-gradle, the play button become stop button. if i have to run another new instance, i have to click the stop button in order to stop the current running instance, which is not what i hope to achieve.

**Comment by badsyntax** [comment]
I wasn't aware there'd be use cases like this. Do you happen to know how other editors might handle this scenario (eh intellij)? Not sure how best to support this tbh. Do you have suggestions on how the UX could work?

**Comment by hannah23280** [comment]
> I wasn't aware there'd be use cases like this. Do you happen to know how other editors might handle this scenario (eh intellij)? Not sure how best to support this tbh. Do you have suggestions on how the UX could work?

I tried it out on intellij. I can execute the bootRun (gradle task for running spring boot  app) twice, provided i enable the option "Allow Parallel Run". If i did not enable it, intellij will not allow me to run the 2nd time.  

What intellij do is that, it just simply open a new terminal-like console for each instance and run

![image](https://user-images.githubusercontent.com/4410920/100454206-6a18d600-30f7-11eb-9b22-614f5a314ade.png)
![image](https://user-images.githubusercontent.com/4410920/100454099-33db5680-30f7-11eb-8108-68b59e31e847.png)

**Comment by hannah23280** [comment]
My visual is as follows:
Once i run the task, there is no need to change the play button to stop button. Continue to display the play button, so that developer can click on it to run new instance (in a new terminal).   If they want to stop a particular instance, they can go to the RECENT Task to stop.

**Comment by hannah23280** [comment]
Hi , any consideration to implement this useful feature?

**Comment by CsCherrYY** [comment]
closed in #1045
