### ISSUE TITLE
Gradle Tasks hung while executing multiple times

### ISSUE THREAD

**Issue by nes-a-cti** [microsoft/vscode-gradle#848]
Extension Name: vscode-gradle
Extension Version: v3.5.2
OS Version: MacOS Big Sur 11.2.1
VSCode version:  1.53.2

**Describe the bug**

While executing Gradle Tasks multiple times, the task execution is getting hung and getting error "Build cancelled: build: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-6.5.1-bin.zip'". Once we hit this error, we cannot execute any other task. It keeps on showing this error.

**To Reproduce**
Step 1. Execute "Build" task. (First executes fine.)
Step 2. On completion of "Build" task, try again the build task.

The behaviour is inconsistant here. Some time we get the error on 2nd execution onwards, sometimes we get the error on 3rd/4th execution.

**Expected behavior**
We should be able to execute gradle tasks multiple times without any error.

**Screenshots**
![Screen Recording 2021-02-15 at 2 08 06 PM](https://user-images.githubusercontent.com/1773811/107928401-477fb600-6f9e-11eb-8e65-d3d7ee45d7b5.gif)

**Output from "Gradle Tasks"**
[debug] [gradle-server] Starting server
[debug] [gradle-server] Gradle Server cmd: /Users/neel/.vscode/extensions/richardwillis.vscode-gradle-3.5.2/lib/gradle-server 53366
[debug] Refreshing tasks
[info] [gradle-server] Server started, listening on 53366
[info] Gradle client connected to server
[info] Java Home: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
[info] JVM Args: --add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=GB,-Duser.language=en,-Duser.variant
[info] Gradle User Home: /Users/neel/.sdkman/candidates/gradle/6.5.1
[info] Gradle Version: 6.5.1
[debug] Get daemon status
[info] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5.1/userguide/command_line_interface.html#sec:command_line_warnings

CONFIGURE SUCCESSFUL in 7s
[info] Found 99 tasks
[debug] Get daemon status
[debug] Get daemon status
[info] Completed build: build
[debug] Get daemon status
[info] Cancel build: Cancel build requested
[info] Build cancelled: build: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-6.5.1-bin.zip'.
[info] Completed build: build
[debug] Get daemon status
[debug] Refreshing tasks
[info] Java Home: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
[info] JVM Args: --add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=GB,-Duser.language=en,-Duser.variant
[info] Gradle User Home: /Users/neel/.sdkman/candidates/gradle/6.5.1
[info] Gradle Version: 6.5.1
[debug] Get daemon status
[info] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5.1/userguide/command_line_interface.html#sec:command_line_warnings

CONFIGURE SUCCESSFUL in 1s
[info] Found 99 tasks
[debug] Get daemon status
[info] Cancel build: Cancel build requested
[info] Build cancelled: build: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-6.5.1-bin.zip'.
[info] Completed build: build
[debug] Get daemon status
[debug] Refreshing tasks
[info] Java Home: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
[info] JVM Args: --add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=GB,-Duser.language=en,-Duser.variant
[info] Gradle User Home: /Users/neel/.sdkman/candidates/gradle/6.5.1
[info] Gradle Version: 6.5.1
[debug] Get daemon status
[info] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5.1/userguide/command_line_interface.html#sec:command_line_warnings

CONFIGURE SUCCESSFUL in 1s
[info] Found 99 tasks
[debug] Get daemon status
[info] Cancel build: Cancel build requested
[info] Build cancelled: build: Could not execute build using Gradle distribution 'https://services.gradle.org/distributions/gradle-6.5.1-bin.zip'.
[info] Completed build: build
[debug] Get daemon status

**Does the bug still exist if you disable all other extensions?**
Yes

**Additional context**

**Comment by fdasoghe** [comment]
Same to me:

Ubuntu 18.04
Gradle 6.5.1
VSCode 1.53.1
Extension Version: v3.5.2
openjdk version "11" 2018-09-25

**Comment by hannah23280** [comment]
Seem to me that the author has not been present for a period of time. Hope he is safe and well.
To that end, seem like someone need to continue with a fork of this project.

**Comment by RobMaskell** [comment]
Same error with my compilesass task

**Comment by badsyntax** [comment]
> Seem to me that the author has not been present for a period of time. Hope he is safe and well.
To that end, seem like someone need to continue with a fork of this project.

Sometimes life gets in the way of open source. I don't see a reason for someone to fork, and that's somewhat of an offensive suggestion. I am happy to accept help! If anyone wants to send a PR, I will happily review it. Otherwise I will try look into this on the weekend, but I am overwhelmed with many things at the moment and can't make any promises.

**Comment by fdasoghe** [comment]
Well, knowing you (@badsyntax ) aknowledge the issue is already a relief. Take your time, of course. 
I'm not able to create a PR but if there's an error log or some other useful info we can provide, please let us know.

**Comment by badsyntax** [comment]
Thanks @think01, logs will probably be useful but I'll let you know if I need them. 

I'm sorry for not replying earlier. I am not ignoring this project, just my life has taken a different path recently. I will do my best to fix this bug on the weekend 👍

**Comment by hannah23280** [comment]
> > Seem to me that the author has not been present for a period of time. Hope he is safe and well.
> > To that end, seem like someone need to continue with a fork of this project.
> 
> Sometimes life gets in the way of open source. I don't see a reason for someone to fork, and that's somewhat of an offensive suggestion. I am happy to accept help! If anyone wants to send a PR, I will happily review it. Otherwise I will try look into this on the weekend, but I am overwhelmed with many things at the moment and can't make any promises.

Hi @badsyntax , really happy to see you back.  Forgive me for mentioning the "fork". It wasn't meant to be an offensive suggestion., but  cos  initially thought something could have happen  (touched wood!) amid the covid period., and a good project like this would be wasted if no one to maintain it.
But now  relief to see you back again.

**Comment by RobMaskell** [comment]
FWIW I tested the same grade tasks after installing TaskExplorer and they seem to be able to repeat them if I run them from there. I'm hoping this rules out the tasks themselves and the gradle version vs code version

**Comment by BavariaBlue** [comment]
Same to me:

Windows 10 Version 10.0.19042 Build 19042
Gradle 6.8.3
VSCode 1.54.1
Extension Version: v3.5.2
openjdk version "15.0.2" latest

**Comment by badsyntax** [comment]
This is a pretty major bug and I can easily replicate it. Sorry for not realising the scale of this bug earlier. The issue is related to the terminal management feature i added in https://github.com/badsyntax/vscode-gradle/pull/748. 
It seems that possibly vscode has changed the terminal event handling which has caused a race condition in this extension. Possibly this bug doesn't exist on older versions of vscode. 

I should be able to get a fix out shortly, but if you need a workaround in the meantime, you can set the following in your vscode settings:

```json
"gradle.reuseTerminals": "off"
```

**Comment by nes-a-cti** [comment]
Hi @badsyntax ,

   Thanks for looking into the issue. Adding the above settings to vscode settings helped to fix the issue.

Thanks

**Comment by badsyntax** [comment]
I have confirmed the source of the issue is due to vscode changing the behaviour of certain apis, which is rather annoying. I have added a fix with https://github.com/badsyntax/vscode-gradle/pull/870 that includes some defensive code to workaround the inconsistencies. The tests are now running against vscode 1.45.0 and 1.54.1 and are passing 🎉  I will release a fix before the end of the weekend.

**Comment by badsyntax** [comment]
I've released the fix, make sure you update to at least 3.6.1. 

Refer to the [3.6.0 release notes](https://github.com/badsyntax/vscode-gradle/releases/tag/3.6.0) for an overview of the changes.

Can you revert the workaround and test the fix for me?

**Comment by RobMaskell** [comment]
@badsyntax  just tested it, LGTM, thanks for the fix

**Comment by BavariaBlue** [comment]
@badsyntax tested for Windows 10
all works fine now :) thanks a lot!
*close issue*

**Comment by badsyntax** [comment]
Thanks for testing!

**Comment by RobMaskell** [comment]
I suspect this might have also fixed an issue I was having with the Spring Boot Dashboard and project initialisation on startup, is was much slower than usual and occasional didn't complete and required a restart. Doesn't seem to be happening now.
Thanks again

**Comment by nes-a-cti** [comment]
Hi @badsyntax ,

    Tested the fix on Mac. It worked well without problem. Thanks for working on it. We can close this issue.

Thanks and Regards

**Comment by fdasoghe** [comment]
@badsyntax thanks for the fix! I can confirm it works on Ubuntu 18.04 :partying_face:
