### ISSUE TITLE
Not detecting gradle tasks in flutter project

### ISSUE THREAD

**Issue by alyyasser** [microsoft/vscode-gradle#86]
i don't know if this is a bug or not, but the extension not detecting gradle tasks in flutter project.
is there any way to detect the tasks manually like in android studio?

**Comment by badsyntax** [comment]
Hi, thanks for the report. It will only detect gradle tasks if a gradle build file exists in the root of the project. Can you try open the android root project and seeing if it can detect gradle tasks?
Can you also describe or post screenshots of the manual detection of tasks in Android studio?
Basically I'm happy to make changes to support this but I'm not sure exactly what changes you'd like.

**Comment by alyyasser** [comment]
tried opening the android root project inside the flutter project, it can detect the tasks.
im not sure how android studio did it, if i remember it correctly, when i open the flutter project without importing it as gradle project, it won't detect the gradle tasks.

is it possible to do lookup for the build.gradle file through all sub-directories inside the root folder/project, not just detecting it by looking in current root folder?

**Comment by alyyasser** [comment]
it's just come into my mind, so i tried it, i create a symlink build.gradle file inside the root folder/project, linked to build.gradle inside /android folder, and it works, it's now can detect the tasks.
i guess, that's the workaround for now.

**Comment by badsyntax** [comment]
There's pros and cons to detecting build files in sub directories. Up till now I didn't think there was any need to check sub directories as the typical setup for gradle projects is to have the build file in the root. I will create an example flutter project to better understand the expected workflow here and get back to you. Great that the symlink workaround works for the meantime.

**Comment by alyyasser** [comment]
the symlink is work somehow, but unfortunely, it show different tasks.
here is the tasks shown after creating symlinked build.gradle 
![symlinked-build.gradle](https://user-images.githubusercontent.com/16476111/70689869-0334be00-1ce8-11ea-8577-03bb2e68de35.png)

and here is the tasks shown when opening android root project
![/android/build.gradle](https://user-images.githubusercontent.com/16476111/70689949-265f6d80-1ce8-11ea-95e4-80e229cc7c1d.png)
![/android/build.gradle](https://user-images.githubusercontent.com/16476111/70690181-b7364900-1ce8-11ea-98c0-5aa70ffaec84.png)

maybe, it might help if there's manual setting for the build.gradle location to choose.

**Comment by badsyntax** [comment]
Thanks for this. I'll replicate this scenario to better understand the problem then I'll propose a solution.

**Comment by badsyntax** [comment]
In the meantime can I ask why you need to run gradle tasks for a flutter app? Seems like most tasks should be run through the flutter cli app. Not saying I won't provide support for this, just curious as to the workflow. Thanks.

**Comment by badsyntax** [comment]
I've got an initial approach working, you can see some screenshot in https://github.com/badsyntax/vscode-gradle/pull/88

**Comment by badsyntax** [comment]
Hey, this should be fixed now. You need to use version ~2.2.5~ 2.2.6. It should now list gradle tasks in nested gradle projects. Let me know if there's any issues, thanks.

**Comment by alyyasser** [comment]
im so sorry for late reply

> In the meantime can I ask why you need to run gradle tasks for a flutter app? Seems like most tasks should be run through the flutter cli app.

as for why i need to run gradle tasks, sometimes i want to run specific tasks, like dumping the keystore used by build task. i can just check it through direct `keystore` command, but it would be nice to just run a gradle task for it :)

anyway, thank you very much for providing support for this, i appreciate it

**Comment by badsyntax** [comment]
No worries, thanks for getting ring back to me, makes sense. I've made the behaviour detect nested gradle projects by default. If this causes issues for users I'll make it configurable. For now it seems ok.
