### ISSUE TITLE
Tasks of common modules appear repeatedly

### ISSUE THREAD

**Issue by mozhuanzuojing** [microsoft/vscode-gradle#877]
Extension Name: vscode-gradle
Extension Version: 3.6.1
OS Version: Windows_NT x64 10.0.17134
VSCode version: 1.57.0-insider (system setup)

**Describe the bug**
Tasks of common modules appear repeatedly

**To Reproduce**
1. common module ampub
2. main moudle fa dependent ampub

**Expected behavior**
The task of the common module only appears once

**Screenshots**
![image](https://user-images.githubusercontent.com/63572041/117749877-12090280-b245-11eb-8f70-0955fdfada17.png)

**Output from "Gradle Tasks"**
You can find this by clicking on the "Output" panel, then selecting the "Gradle Tasks" channel from the dropdown.

**Does the bug still exist if you disable all other extensions?**
Yes

**Additional context**

**Comment by hannah23280** [comment]
I encounter this earlier.  While i trying to recall how i solved that, can i ask if u are using nested gradle projects

**Comment by CsCherrYY** [comment]
could you provide a sample project to help us reproduce this issue?

**Comment by mozhuanzuojing** [comment]
> could you provide a sample project to help us reproduce this issue?

@CsCherrYY I modify project construct . No problems! Thanks for your notice!
