### ISSUE TITLE
run task before set cmd env encoding to utf8

### ISSUE THREAD

**Issue by mozhuanzuojing** [microsoft/vscode-gradle#911]
Extension Name: vscode-gradle
Extension Version:3.6.1
OS Version:windows21h1
VSCode version:1.59

**Describe the bug**

gradle view run task in cmd no set env encoding to utf8. but now task print utf8 char ,cmd encoding is cp936 (gbk). so cmd show error char

**To Reproduce**
1. Define a simple task:
```gradle
task print(){
      doLast{
      println “echo Chinese: 中文”
      }
}
```
2. Run print in gradle view

**Expected behavior**

output ***echovChinese: 中文***

**Screenshots**

**Output from "Gradle Tasks"**
You can find this by clicking on the "Output" panel, then selecting the "Gradle Tasks" channel from the dropdown.

**Does the bug still exist if you disable all other extensions?**
Yes

**Additional context**

**Comment by CsCherrYY** [comment]
I can't reproduce this bug in the newest version `3.8.2`, this issue seems to be resolved. @mozhuanzuojing Could you please try to verify?

**Comment by mozhuanzuojing** [comment]
> I can't reproduce this bug in the newest version `3.8.2`, this issue seems to be resolved. @mozhuanzuojing Could you please try to verify?

@CsCherrYY it work .thank you
