### ISSUE TITLE
!Important Gradle daemon view only show part of all Gradle Deamon JVM

### ISSUE THREAD

**Issue by mozhuanzuojing** [microsoft/vscode-gradle#930]
Extension Name: vscode-gradle
Extension Version:3.6.1
OS Version:window10
VSCode version: 1.60.0-insider (system setup)

**Describe the bug**

When I open the gradle deamon view and wait a few seconds. Execute `jps -l -m -v` to see two Deamon. But Gradle Deamon View can only see one.

One of the Gradle Deamon JVMs is started by the vscode-java plugin, Another Gradle Deamon JVM is started by the vscode-gradle plugin. But both Deamon are analyzing the same project! Repeat it!

**To Reproduce**
1. Open a gradle project
2. Await build job finished
3. Open gradle deamon view

**Expected behavior**
Show all current gradle deamon jvm of running.

**Screenshots**

![image](https://user-images.githubusercontent.com/63572041/130549796-313fb269-2641-41af-9a92-8ff8c88c8c79.png)

**Output from "Gradle Tasks"**

**Does the bug still exist if you disable all other extensions?**
Yes

**Additional context**

**Comment by CsCherrYY** [comment]
@mozhuanzuojing Could you try to click `Refresh Daemon Status` button? Does it work?

**Comment by mozhuanzuojing** [comment]
@CsCherrYY 

- No display after clicking refresh

![image](https://user-images.githubusercontent.com/63572041/130384068-05cfd570-fa1f-41e2-89ec-fccf7d483cfc.png)

**Comment by mozhuanzuojing** [comment]
@CsCherrYY There are two Gradle deamon JVMs but only one is displayed.

![image](https://user-images.githubusercontent.com/63572041/130549847-cdb1fec6-c155-4929-8c08-ba460f12e21a.png)

**Comment by mozhuanzuojing** [comment]
@CsCherrYY  I re-describe the issue.

## A serious problem was found. The vscode-java plugin starts a Gradle Deamon JVM. Then I executed Gradle Task from the Gradle view, it restarted a new Gradle Deamon JVM！

**Comment by mozhuanzuojing** [comment]
@CsCherrYY I hope that the next version can reuse the existing Gradle Deamon. Because I don't want to wait for the project to compile. And reduce calls to `Java: Update Project`. Thanks.

**Comment by CsCherrYY** [comment]
@mozhuanzuojing That's also what we want to improve in the future 😄. `vscode-gradle` could have a better way to collaborate with `vscode-java`.

**Comment by mozhuanzuojing** [comment]
Duplicate of #953

**Comment by CsCherrYY** [comment]
tracked in #953 and will be in Jan 2022 milestone.
