### ISSUE TITLE
The email of the supervisor of the vscode.gradle team sent me a message, I need help!

### ISSUE THREAD

**Issue by mozhuanzuojing** [microsoft/vscode-gradle#941]
The email of the supervisor of the vscode.gradle team sent me a message, I need help!

Send me the email of your team
> this is my email 

- mozhuanzuojing2020@163.com

**Comment by CsCherrYY** [comment]
Why not just paste your issue and discuss here?

**Comment by mozhuanzuojing** [comment]
@CsCherrYY  Because there is a plug-in lag problem, I need to send an email to the gradle and java teams to solve it together
