### ISSUE TITLE
First time click `Fresh Gradle Tasks` Recompile all projects！

### ISSUE THREAD

**Issue by mozhuanzuojing** [microsoft/vscode-gradle#944]
Extension Name: vscode-gradle
Extension Version: 3.6.1
OS Version: Windows_NT x64 10.0.19043
VSCode version: 1.60.0-insider (system setup)

**Describe the bug**
When the open workspace stopped operating for 3 hours, returning to the workspace and clicking on `Fresh Gradle Tasks` would cause all the projects to be recompiled, which made me have to stop and wait for 10 minutes! !

**To Reproduce**
1. Open a gradle project
2. await for 3 hours，Don't operate.
3. Open Gradle Tasks view
4. click `Fresh Gradle Tasks` button，only first time click！

**Expected behavior**
Refresh immediately, do not recompile the project, because my project is very large

**Screenshots**
![image](https://user-images.githubusercontent.com/63572041/130713896-b3783b57-12b2-4426-b8d3-69eb2e937df6.png)

**Output from "Gradle Tasks"**
[Gradle Tasks Output.log](https://github.com/microsoft/vscode-gradle/files/7043110/Gradle.Tasks.Output.log)

**Does the bug still exist if you disable all other extensions?**
Yes

**Additional context**

**Comment by CsCherrYY** [comment]
`vscode-java` will start a Gradle daemon and it will become `IDLE` after finishing importing project. 3 hours is the max time for an `IDLE` daemon to become a `STOPPED` daemon, see https://docs.gradle.org/current/userguide/gradle_daemon.html for the reference. I think it might be the root cause. BTW, I see you had opened #943 and #921 and IMO they might be the same root cause. Did you find these issues in the same project? Could you provide a sample project to help me check them?

**Comment by mozhuanzuojing** [comment]
@CsCherrYY I guarantee that Gradle Deamon is alive, i can see it with `jps -l -v -m`

Because my project cannot be shared, so today I will use the springboot source code to test this problem

> my gradle.user.home gradle.properties

```properties

org.gradle.daemon=true  // 开启线程守护，第一次编译时开线程，之后就不会再开了
org.gradle.jvmargs= -XX:MaxMetaspaceSize=512m -XX:+UseShenandoahGC    -Xms1g    -Xmx2g -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=35 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true  -Dsun.jnu.encoding=UTF-8  -Dfile.encoding=UTF-8    -XX:+HeapDumpOnOutOfMemoryError 
org.gradle.parallel=true  // 开启并行编译，相当于多条线程再走
org.gradle.configureondemand=true   // 启用新的孵化模式
# https://docs.gradle.org/current/userguide/build_environment.html#build_environment
# Gradle 守护进程将在指定的空闲毫秒数后自行终止。默认为10800000（3 小时），更新为( 24 小时 )
org.gradle.daemon.idletimeout=86400000
org.gradle.caching=true

```

**Comment by mozhuanzuojing** [comment]
> I see you had opened #943 and #921 and IMO they might be the same root cause

Yes, I feel that it should belong to the same problem.

**Comment by mozhuanzuojing** [comment]
@CsCherrYY Thanks!

Disable the gradle plugin, restart VS Code, and then enable the gradle plugin. The problem does not recur after repeating twice.

> additional, i add following config
```json
"java.configuration.updateBuildConfiguration": "disabled",
"java.debug.settings.forceBuildBeforeLaunch": false
```

**Comment by mozhuanzuojing** [comment]
@CsCherrYY The real cause of this problem is caused by the following configuration. (gradle7.2)

<https://github.com/redhat-developer/vscode-java/wiki/Gradle-Support#performance-degrades-with-gradle-project>
