### ISSUE TITLE
Slack Channel for support is locked

### ISSUE THREAD

**Issue by c4tachan** [microsoft/vscode-gradle#975]
The link to the slack channel for general support takes the user to a login page, where when they log in they are denied access because they don't have an account in the workspace.

Please fix this, or provide an alternate method for requesting support.

**Comment by chozandrias76** [comment]
Also experiencing this issue.

**Comment by CsCherrYY** [comment]
Let's remove this option and provide a blank template to guide you to report the issue and keep the discussions inside this repository.
