### ISSUE TITLE
More auto completion proposals

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-gradle#982]
- When editing in settings.gradle, suggest `"include()"` method.
![image](https://user-images.githubusercontent.com/14052197/132177369-161d6dd9-5aeb-4df7-9a90-bcd1d6b456b9.png)

- suggest the common `dependencies` methods such as `"testImplementation()"` and `"implementation()"`.

**Comment by CsCherrYY** [comment]
also for those Gradle types which have supertypes, like `org.gradle.api.Project` extends `org.gradle.api.plugins.PluginAware`, the available methods in that supertype should be listed in the completion.
