### ISSUE TITLE
Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by TheAifam5** [microsoft/vscode-gradle#99]
**Describe the bug**
It crashes with following error:
```
TypeError: Cannot read property '0' of undefined
	at Function.file (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:126)
	at /home/theaifam5/.vscode-java/richardwillis.vscode-gradle-2.2.6/out/gradleView.js:264
	at Array.forEach (<anonymous>)
	at GradleTasksTreeDataProvider.buildTaskTree (/home/theaifam5/.vscode-java/richardwillis.vscode-gradle-2.2.6/out/gradleView.js:241)
	at GradleTasksTreeDataProvider.<anonymous> (/home/theaifam5/.vscode-java/richardwillis.vscode-gradle-2.2.6/out/gradleView.js:207)
	at Generator.next (<anonymous>)
	at fulfilled (/home/theaifam5/.vscode-java/richardwillis.vscode-gradle-2.2.6/out/gradleView.js:5)
onDidNotificationChange @ notificationsAlerts.ts:38
notificationsAlerts.ts:38 TypeError: Cannot read property '0' of undefined
	at Function.file (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:126)
	at /home/theaifam5/.vscode-java/richardwillis.vscode-gradle-2.2.6/out/gradleView.js:264
	at Array.forEach (<anonymous>)
	at GradleTasksTreeDataProvider.buildTaskTree (/home/theaifam5/.vscode-java/richardwillis.vscode-gradle-2.2.6/out/gradleView.js:241)
	at GradleTasksTreeDataProvider.<anonymous> (/home/theaifam5/.vscode-java/richardwillis.vscode-gradle-2.2.6/out/gradleView.js:207)
	at Generator.next (<anonymous>)
	at fulfilled (/home/theaifam5/.vscode-java/richardwillis.vscode-gradle-2.2.6/out/gradleView.js:5)
	at o (/home/theaifam5/.vscode-java/vscjava.vscode-java-test-0.22.0/dist/extension.bundle.js:9)
	at /home/theaifam5/.vscode-java/vscjava.vscode-java-test-0.22.0/dist/extension.bundle.js:9
```
Crashes in that scope:
https://github.com/badsyntax/vscode-gradle/blob/9c248eff1c6ebe79bc6d3185caa60d787329aa7a/src/gradleView.ts#L340

**To Reproduce**
Use example from `https://github.com/FabricMC/fabric-example-mod`.

**Expected behavior**
Should show gradle tasks.

**Screenshots**
![image](https://user-images.githubusercontent.com/2192274/70853717-f19f1200-1eb1-11ea-815c-2118277313e9.png)

**Environment:**

- OS: ArchLinux
- Java: 
```
openjdk 11.0.5 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10)
OpenJDK 64-Bit Server VM (build 11.0.5+10, mixed mode)
```
- Gradle: 5.5.1

**Output from "Gradle Tasks"**
```
./gradle-tasks /home/theaifam5/Documents/Projects/TheAifam5/Java/example-fabric-mod /tmp/vscode-gradle-4QurBq/tasks.json
.........................................
> Configure project :
Fabric Loom: 0.2.7-SNAPSHOT Build(jenkins #9)
:setting up loom dependencies
:setting up mappings (yarn 1.15+build.2)
....
CONFIGURE SUCCESSFUL in 741ms
..............................................
> Configure project :
Fabric Loom: 0.2.7-SNAPSHOT Build(jenkins #9)
:setting up loom dependencies
:setting up mappings (yarn 1.15+build.2)

CONFIGURE SUCCESSFUL in 289ms
.
Successfully written: /tmp/vscode-gradle-4QurBq/tasks.json
```

**Additional context**
/tmp/vscode-gradle-2r3NWD/tasks.json:
[output.zip](https://github.com/badsyntax/vscode-gradle/files/3964260/output.zip)

**Comment by badsyntax** [comment]
I wonder if this is due to a conflict with another extension. Can you try disable all other extensions, and just enable this extension and see if it works?

**Comment by TheAifam5** [comment]
You're right, it's because of `spmeesseman.vscode-taskexplorer`. This `spmeesseman.vscode-taskexplorer` extension shows only `sourcesJar` task, that's why I installed yours.

I spotted also that issue with your comment: https://github.com/spmeesseman/vscode-taskexplorer/issues/26

**Comment by badsyntax** [comment]
Thanks for letting me know. In the past I provided support for running vscode-gradle alongside that extension but couldn't maintain compatibility. I will have another look.

**Comment by TheAifam5** [comment]
Even setting `"taskExplorer.enableGradle": false` does not help. For now I'm gonna disable `vscode-taskexplorer`.

**Comment by badsyntax** [comment]
Thanks for this. vscode-taskexplorer is no good at detecting gradle tasks as it just does a string match within the gradle file instead of using gradle to provide the tasks. Ideally vscode-gradle should provide the tasks for vscode-taskexplorer but for some reason the gradle task definitions are replaced with something else (hence the error you see) and I can't figure out why. I'm not even sure if, by design, multiple extensions can provide the same task types, so I'm not sure there's a generic solution here. I'm considering to make a change to vscode-taskexplorer to prevent providing its own gradle tasks if vscode-gradle extension is enabled, but I'm not sure if I can even do that, as task definitions are defined within package.json ("before" runtime). I'll keep this ticket open whilst I try different things. I can't give an ETA due to the amount of unknowns but I will try provide some compatibility as I understand vscode-taskexplorer is quite useful for some. In the meantime you'll have to disable vscode-taskexplorer if you want to use vscode-gradle. Thanks for the detailed bug report btw!

**Comment by badsyntax** [comment]
Hey, I've decided there's not much I can do about this. Both extensions are attempting to provide tasks of the same type and i'm not willing to change the task type.

I've added some information about the incompatibly to the README with #188. Sorry about this.
